// Compatibility entry; construction belongs to core application assembly.
import { workAuditCensus } from "../application/default.mjs";
export const {
  AUDIT_FINDING_CODES,
  CENSUS_SWEEPS,
  LEDGER_PROJECT,
  LIMIT_KEYS,
  PROBE_PROGRAM,
  SWEEP_BASES,
  TEST_ROOTS,
  UNREGISTERED_BASELINE,
  assembledSuite,
  assertSweepsDeclared,
  baselineProblems,
  ledgerApplies,
  limitDeclarationProblems,
  limitRecord,
  readFinding,
  readRecord,
  readRegistrationIndexes,
  registrationDecision,
  registrationSources,
  runCensus,
  runnerBindings,
  runnerImportedSuites,
  runnerSpreadNames,
  spreadClaimLimit,
  sweepDeclarationProblems,
  sweepLimits,
  walkSuiteFiles,
} = workAuditCensus;
