// Compatibility entry; construction belongs to core application assembly.
import { workAuditReport } from "../application/default.mjs";
export const {
  AUDITABLE_CODES,
  AUDIT_ENVELOPE_KEYS,
  AUDIT_FACE_CODES,
  ESCALATING_CODES,
  LANE_NEUTRAL_CODES,
  OWNING_KEYS,
  REPORT_LANES,
  addresseesFor,
  assertLaneLimits,
  assertLaneRead,
  assertLaneRunnersDistinct,
  auditableCodesFor,
  auditorFindings,
  auditorOf,
  auditorsOf,
  canReceive,
  declaredPointerRaws,
  escalates,
  escalationActorOf,
  instrumentFor,
  laneVocabularyCollisions,
  matchesScope,
  ownersOfInstrument,
  pointerFile,
  referenceSettersOf,
  resolveAddressees,
  runAudit,
  runRegistryChecks,
  unreportedFloorFindings,
} = workAuditReport;
