// Compatibility entry; construction belongs to core application assembly.
import { workDispatch } from "../application/default.mjs";
export const {
  DEFAULT_DISPATCH_CONCURRENCY,
  DEFAULT_LANE_QUIET_MS,
  cleanupDispatchLane,
  commitDispatchLane,
  dispatchConcurrencyFromConfig,
  dispatchLaneBase,
  dispatchLaneOccupiesSlot,
  dispatchReadySet,
  inspectDispatchLaneAdmission,
  inspectDispatchLanes,
  laneChanges,
  mergeDispatchLaneHome,
  narrowDispatchBound,
  overlappingFiles,
  planDispatchLaneAdmissions,
  resolveDispatchConcurrency,
  resolveDispatchLane,
  resolveRefInWorktree,
  sweepDispatchLanes,
  withDispatchLaneAdmissionLock,
  worktreeWorkDir,
} = workDispatch;
