import path from "node:path";

const GENERATED_NOTICE = "<!-- Generated by AOF. Do not edit directly; update .aof/ instead. -->";

export function claudeMcpJson(servers) {
  const mcpServers = {};
  for (const server of sortById(servers)) {
    mcpServers[server.id] = withoutEmpty({
      type: server.transport,
      command: server.command,
      args: server.args,
      env: server.env,
      url: server.url,
      headers: server.headers,
      ...runtimeExtension(server, "claude")
    });
  }
  return jsonContent({ mcpServers });
}

// m43 / ADR-002 AC11 — `claudeSettingsJson` IS GONE, not merely unused. It built the
// ENTIRE `.claude/settings.json` body from `config.hooks` + `config.settings`, which
// is only ever correct for a file aof exclusively owns; that file is CO-AUTHORED. The
// claude runtime's hooks and settings now reach it through the surgical merge in
// `src/claude-settings.mjs`. Deleting the renderer rather than leaving it exported and
// uncalled is the point: a whole-file writer for a co-authored file that still exists
// is a whole-file writer someone will call.

export function codexConfigToml({ mcpServers = [], hooks = [], settings = {} } = {}) {
  const body = { ...runtimeSettings(settings, "codex") };
  const servers = codexMcpServers(mcpServers);
  const renderedHooks = codexHooks(hooks);
  if (Object.keys(servers).length > 0) body.mcp_servers = servers;
  if (Object.keys(renderedHooks).length > 0) body.hooks = renderedHooks;
  return toToml(body);
}

export function codexHooksJson(hooks = []) {
  return jsonContent({ hooks: codexHooks(hooks) });
}

export function projectDocContent(target, docs) {
  const sorted = sortById(docs).filter((doc) => doc.targets.includes(target));
  return [
    "# AOF Generated Project Guidance",
    "",
    GENERATED_NOTICE,
    "",
    ...sorted.flatMap((doc) => [
      `## ${doc.name ?? doc.id}`,
      "",
      doc.description ? `> ${doc.description}` : null,
      "",
      contentFor(doc).trim(),
      ""
    ].filter((line) => line !== null))
  ].join("\n");
}

export function toToml(value) {
  if (!isPlainObject(value)) {
    throw new Error("TOML root must be an object.");
  }

  const lines = [];
  writeTomlObject(lines, [], value);
  return `${lines.join("\n").trimEnd()}\n`;
}

function writeTomlObject(lines, tablePath, object) {
  const keys = Object.keys(object).sort();
  const scalarKeys = keys.filter((key) => isTomlScalarValue(object[key]));
  const tableKeys = keys.filter((key) => isPlainObject(object[key]));
  const arrayTableKeys = keys.filter((key) => isArrayOfTables(object[key]));

  for (const key of scalarKeys) {
    lines.push(`${quoteKey(key)} = ${tomlValue(object[key])}`);
  }

  for (const key of tableKeys) {
    if (lines.length > 0) lines.push("");
    const nextPath = [...tablePath, key];
    lines.push(`[${nextPath.map(quoteKey).join(".")}]`);
    writeTomlObject(lines, nextPath, object[key]);
  }

  for (const key of arrayTableKeys) {
    const nextPath = [...tablePath, key];
    for (const item of object[key]) {
      if (lines.length > 0) lines.push("");
      lines.push(`[[${nextPath.map(quoteKey).join(".")}]]`);
      writeTomlObject(lines, nextPath, item);
    }
  }
}

function codexMcpServers(servers) {
  const rendered = {};
  for (const server of sortById(servers)) {
    rendered[server.id] = withoutEmpty({
      transport: server.transport,
      command: server.command,
      args: server.args,
      env: server.env,
      url: server.url,
      headers: server.headers,
      ...runtimeExtension(server, "codex")
    });
  }
  return rendered;
}

function codexHooks(hooks) {
  const byEvent = {};
  for (const hook of sortById(hooks)) {
    const group = byEvent[hook.event] ?? [];
    group.push(withoutEmpty({
      matcher: hook.matcher,
      hooks: [
        withoutEmpty({
          type: hook.type,
          command: hook.command,
          ...runtimeExtension(hook, "codex")
        })
      ]
    }));
    byEvent[hook.event] = group;
  }
  return byEvent;
}

function runtimeSettings(settings, runtime) {
  const runtimeSpecific = settings?.[runtime];
  if (!runtimeSpecific || typeof runtimeSpecific !== "object" || Array.isArray(runtimeSpecific)) {
    return {};
  }
  return { ...runtimeSpecific };
}

function runtimeExtension(value, runtime) {
  const extension = value?.[runtime];
  if (!extension || typeof extension !== "object" || Array.isArray(extension)) return {};
  return extension;
}

function jsonContent(value) {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function contentFor(doc) {
  return doc.body ?? doc.prompt ?? doc.instructions ?? "";
}

function sortById(items) {
  return [...items].sort((a, b) => a.id.localeCompare(b.id));
}

function withoutEmpty(value) {
  return Object.fromEntries(Object.entries(value).filter(([, entry]) => entry !== undefined));
}

function isTomlScalarValue(value) {
  if (value === null || value === undefined) return false;
  if (Array.isArray(value)) return !value.some((item) => isPlainObject(item));
  return !isPlainObject(value);
}

function isArrayOfTables(value) {
  return Array.isArray(value) && value.every(isPlainObject);
}

function tomlValue(value) {
  if (typeof value === "string") return JSON.stringify(value);
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number" && Number.isFinite(value)) return String(value);
  if (Array.isArray(value)) return `[${value.map(tomlValue).join(", ")}]`;
  throw new Error(`Unsupported TOML value at runtime config: ${String(value)}`);
}

function quoteKey(key) {
  return /^[A-Za-z0-9_-]+$/.test(key) ? key : JSON.stringify(key);
}

function isPlainObject(value) {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value) && value.constructor === Object;
}

export function targetForProjectDocRuntime(runtime) {
  if (runtime === "codex") return "AGENTS.md";
  if (runtime === "claude") return "CLAUDE.md";
  if (runtime === "opencode") return "AGENTS.md";
  return null;
}

export function projectDocOutputPath(targetDir, target) {
  return path.join(targetDir, target);
}
