// Compatibility entry; construction belongs to core application assembly.
import { commandsLoop } from "../application/default.mjs";
export const {
  DOCTOR_GATE_CODES,
  LOOP_FIX_TRANSPORT_KEYS,
  SHELL_LOOP_ID,
  admitResumeBuildRun,
  admittedDoctorFindings,
  applyGradeBaseline,
  failingCountFromGrade,
  fixTransport,
  gradeFindings,
  gradeRoute,
  gradeStopCode,
  gradeStopProducer,
  gradeSummary,
  loopCommand,
  mergeGateFindings,
  readGradeBaseline,
  recordBuildProgress,
  renderLoopState,
  runLoopBody,
  runLoopLaunch,
  thinkingNarration,
} = commandsLoop;
