// Compatibility entry; construction belongs to core application assembly.
import { commandsTrigger } from "../application/default.mjs";
export const {
  LEVEL_FLAG,
  LOOP_INPUT_KEYS,
  RESOLVED_TRIGGER_KEYS,
  TRIGGER_GATE_READING_FAILED,
  TRIGGER_GATE_READING_UNOBTAINED,
  TRIGGER_GATE_READING_UNREACHABLE,
  TRIGGER_LOOP_UNREGISTERED,
  TRIGGER_SIGNAL_UNMATCHED,
  TRIGGER_SIGNAL_UNREADABLE,
  TRIGGER_SOURCE_UNDECLARED_GAP,
  TRIGGER_SOURCE_UNKNOWN,
  TRIGGER_SOURCE_UNRESOLVABLE_HERE,
  TRIGGER_SOURCE_UNRESOLVED_GAP,
  TRIGGER_UNKNOWN,
  buildTriggerReport,
  triggerCommand,
} = commandsTrigger;
