<!-- aof-generated: refine (Three Amigos — PO headline Scenarios, QA Examples + litmus) -->

# Task feature — the changelog is a PURE PROJECTION of WORK_ITEM_MIGRATIONS: a generator
# produces one entry per transform descriptor, the committed artifact carries the
# `aof-generated` stamp, and regenerate == committed is the drift guard that makes a
# hand edit impossible to sustain (ADR-006; fitness acd-changelog-generated).
#
# LITMUS: every Then is confirmable from one of three black-box seams — never a source
# read — and each scenario's comment names which:
#   (a) THE REGENERATED OUTPUT — the changelog generator (the projection over
#       WORK_ITEM_MIGRATIONS in src/work-upgrade.mjs, indicatively renderChangelog /
#       generateChangelog) invoked on a fixture registry or on the current registry; its
#       returned/emitted text is read directly.
#   (b) THE COMMITTED ARTIFACT ON DISK — the git-tracked changelog file story 04 commits;
#       read as a file / `git show` (the exact path is story-04-defined — treated here as
#       "the committed changelog artifact").
#   (c) THE `aof upgrade` CLI PLAN — a fresh `aof upgrade --dry-run --json` read (story 02),
#       used ONLY to prove the changelog never feeds back into what the engine executes.
# Story 04 owns the exact regenerate surface (a CLI emit and/or the drift-guard check) and
# the committed artifact path; as with story 01's engine (m41 reindex), the generator may
# be called via its API in the When, but every OUTCOME is read back through (a)/(b)/(c).
# PRECONDITION the drift guard rests on: the generator is DETERMINISTIC — its body is a
# pure function of the registry descriptors, carrying NO volatile timestamp or per-release
# value, and the stamp is the stable form (`<!-- aof-generated: … -->` / `aof-generated:
# true`, never a dated one) — else regenerate == committed cannot hold across runs.

@cli @work @work-stream
Feature: the upgrade changelog is generated from WORK_ITEM_MIGRATIONS and cannot drift from it
  In order that "how do I upgrade" resolves to a command and never to prose that binds nobody and rots
  the moment the next transform lands (the passive-note failure this stream abolishes),
  the changelog must be a pure projection of the migration registry — one entry per transform, carrying
  the `aof-generated` stamp — such that regenerating reproduces the committed artifact byte-for-byte and
  a hand edit cannot survive.

  Background:
    Given the changelog is a pure projection of `WORK_ITEM_MIGRATIONS`, generated by `work-upgrade.mjs` and committed to the repo as an `aof-generated` artifact

  # SEAM (a) regenerated output. The projection cannot OMIT a registered transform nor
  # INVENT one — the entry count tracks the registry cardinality exactly. Proven on a
  # fixture registry so the count is deterministic; no source read.
  @executable
  Scenario: the changelog has exactly one entry per registered transform — it cannot omit or invent one
    Given a fixture `WORK_ITEM_MIGRATIONS` registry of exactly 3 contiguous transforms (0→1, 1→2, 2→3)
    When the changelog is generated from that fixture registry
    Then the generated output contains exactly 3 transform entries — one per descriptor
    And regenerating after removing the "2→3" transform yields exactly 2 entries
    And regenerating after appending a "3→4" transform yields exactly 4 entries

  # SEAM (a) regenerated output. Each entry is a projection of its descriptor's four fields
  # — id / from→to / summary. The Examples table is QA's: it enumerates the descriptor
  # shapes the generator must render (the 0→1 stamp transform that always exists per
  # ADR-003, plus fixture successors).
  @executable
  Scenario Outline: each changelog entry projects its descriptor's id, from→to step, and summary
    Given a fixture `WORK_ITEM_MIGRATIONS` registry containing a transform "<id>" from schema <from> to schema <to> summarised "<summary>"
    When the changelog is generated from that fixture registry
    Then the generated output contains an entry for transform "<id>"
    And that entry shows the step from schema <from> to schema <to>
    And that entry carries the summary "<summary>"

    Examples: transform descriptors projected into changelog entries
      | id                  | from | to | summary                                                      |
      | stamp-schema-0-to-1 | 0    | 1  | stamp an unstamped item schema:1 + aofVersion (the backstamp)|
      | fixture-1-to-2      | 1    | 2  | add the example frontmatter key introduced at schema 2       |
      | fixture-2-to-3      | 2    | 3  | rename the example sibling doc introduced at schema 3        |

  # SEAM (a)+(b) regenerated output vs committed artifact on disk. THE load-bearing
  # property: regenerate == committed, byte-for-byte. Determinism is asserted so the guard
  # is stable across runs (the precondition in the LITMUS block, made checkable here).
  @executable
  Scenario: the drift guard — regenerating from the current registry reproduces the committed artifact byte-for-byte
    When the changelog is regenerated from the current `WORK_ITEM_MIGRATIONS`
    Then the regenerated output is byte-for-byte identical to the committed changelog artifact on disk
    And regenerating a second time from the same registry produces byte-identical output (deterministic — no volatile timestamp or per-release value in the body)

  # SEAM (a)+(b) regenerated output vs committed artifact on disk. The other half of the
  # guard: a hand edit to the committed file is DETECTED, because the only sanctioned way to
  # change the changelog is to change the registry and regenerate.
  @executable
  Scenario: a hand edit to the committed changelog fails the drift guard
    Given the committed changelog artifact has been hand-edited (a line of prose added by hand)
    When the changelog is regenerated from the current `WORK_ITEM_MIGRATIONS` and compared to the committed artifact on disk
    Then the regenerated output no longer matches the committed artifact byte-for-byte
    And the drift guard reports the committed changelog as drifted from the registry

  # SEAM (a)+(b) regenerated output / committed artifact on disk. The artifact is
  # self-identifying: it carries the `aof-generated` marker in a canonical 01/ADR-005 form,
  # so a reader — human or the drift guard — can tell it is generated, not hand-authored.
  @executable
  Scenario: the generated changelog is self-identifying — it carries the `aof-generated` stamp
    When the changelog is generated from the registry
    Then the generated output carries the `aof-generated` marker in a canonical form (a leading `<!-- aof-generated: … -->` comment or an `aof-generated: true` frontmatter key)
    And the committed changelog artifact on disk carries that same `aof-generated` stamp

  # SEAM (a) regenerated output + (c) `aof upgrade --dry-run` CLI plan. The generator reads
  # the registry, NEVER the reverse — the changelog is a downstream-only projection with no
  # feedback edge. Confirmed behaviourally (no import-graph source read): a registry change
  # flows INTO the changelog, but an edit to the changelog flows into NOTHING.
  @executable
  Scenario: the changelog is downstream-only — the generator reads the registry, never the reverse
    When a transform is added to `WORK_ITEM_MIGRATIONS` and the changelog is regenerated
    Then the regenerated changelog gains an entry for the new transform (registry → changelog is live)
    And after the committed changelog is instead hand-edited, a fresh `aof upgrade --dry-run --json` plans the identical transform chain (changelog → registry is dead — no feedback edge)

  # SEAM (a)+(b) — the real delivery, run by the developer against the LIVE repo registry.
  # @manual because it regenerates from the current `WORK_ITEM_MIGRATIONS`, diffs against the
  # committed file, and records the byte-identity in VERIFICATION.md (mirrors story 02's
  # @manual backstamp). The @executable scenarios above prove the mechanism deterministically.
  @manual
  Scenario: the committed changelog matches regeneration from the current registry, and "how do I upgrade" resolves to `aof upgrade`
    Given the changelog committed in the aof repo
    When the developer regenerates it from the current `WORK_ITEM_MIGRATIONS` and diffs against the committed file
    Then the regeneration is byte-for-byte identical to the committed artifact, and the developer records the byte-identity in VERIFICATION.md
    And the committed changelog names `aof upgrade` as the act of upgrading — "how do I upgrade" resolves to the command, not to prose
    And the changelog carries no load-bearing advice that would rot when the next transform lands
