// Compatibility entry; construction belongs to core application assembly.
import { workAuditEvidence } from "../application/default.mjs";
export const {
  DRIVE_PROGRAM,
  DRIVE_RESULT_SENTINEL,
  EVIDENCE_FINDING_CODES,
  EVIDENCE_SWEEP,
  EVIDENCE_VERDICTS,
  MESSAGE_NORMALISATIONS,
  REGISTRATION_LIMIT,
  REPRODUCED_VERDICTS,
  SIZE_KINDS,
  cellUnder,
  dispositionOf,
  driveControl,
  findingsForRow,
  messagesAgree,
  normalizeMessage,
  observeControl,
  observedMessage,
  parseDriveOutput,
  recordedCasesIn,
  recordedMessageIn,
  recordedResultIn,
  recordedRowsFor,
  runEvidence,
  sizeFor,
  verdictFor,
} = workAuditEvidence;
