@executable @cli @work @work-stream
Feature: `src/bundle/loops/` is the single source — this repo's `.aof/loops/` is an INSTALLED artifact aof dogfoods

  ADR-012 §6 rules the question the STORY left implicit and that decides where every test points:
  the nine records live at `src/bundle/loops/` as the **one** source of truth, `wiki/work/loops/` is
  `git mv`'d there and ceases to exist, and this repository's own `.aof/loops/` is an installed,
  git-tracked artifact regenerated by `aof work update`. Hand-maintaining `.aof/loops/` and copying
  it into the bundle is refused by name — it is TECH_DEBT item 0's headline shape ("the same fact
  derived independently, everywhere") committed on nine files, and the copy would drift the first
  time a record was corrected in the wrong half.

  The consequence is that **aof eats its own delivery**: the registry aof's own suites read is the
  registry aof ships, arrived by the same pipeline a consumer's does. That is the strongest available
  evidence for the story's claim, and it is only evidence if the two halves are pinned equal —
  otherwise it is the story's own defect, reproduced. The hazard is measured, not hypothetical:
  hashing all 86 shipped `src/bundle/manifest.json` entries against this repo on 2026-08-15 gives
  **75 ok / 11 drifted / 0 missing**, and nothing fails today. Dogfooding the registry without a
  byte-equality leg would hand the two real-registry suites a stale-green subject — reading an
  installed copy that no longer matches what ships. The general gap is routed as TECH_DEBT item 54;
  the nine records are pinned here.

  **The byte-equality leg compares against `src/bundle/loops/*.md`'s BYTES, not against
  `src/bundle/manifest.json`'s hashes** — and that distinction is the whole value of the leg. The two
  are equivalent only while the manifest is current, and the manifest is measurably not always
  current: `acd-bundle-manifest-hashes` has been RED since commit `d38e720` for exactly this reason.
  A leg written against the manifest would go GREEN while a record corrected in `src/bundle/loops/`
  and never re-installed sat stale on disk — two gates disagreeing, with only one of them naming the
  defect. The manifest is a useful SECOND, independent leg; it is not the referent of the first.

  **Running `aof work update` in this repository is not a clean act, and the story must not pretend
  otherwise.** Measured on HEAD, eleven tracked files outside this story classify `update` — the task
  example template, three `.claude/commands/aof/` files, two `.claude/agents/` files and six under
  `.codex/` — plus `.aof/aof.lock.json`. They are rewritten, not drift-warned. Whoever builds this
  either lands those eleven deliberately in this diff and says so, or excludes them and says that.
  Both are defensible; discovering them in review is not.

  The repoint itself is one expression per file, and the STORY's count was wrong. **Two** files load
  the live registry, not seven: `test/work-loops-registry-census.test.mjs` (`workDir` built at
  `:56-60` from `import.meta.url`, loaded at `:184`) and `test/arch/acd-loop-records-parse.test.mjs`
  (`:29`, `:80`). Each swaps `path.join(root, "wiki", "work")` for `path.join(root, ".aof")`. The
  five files the STORY also named — `work-loops-record`, `work-loops-value`, `work-loops-checks`,
  `work-loops-commands`, `work-loops-coverage-ledger` — reference `wiki/work/...` only to read
  `.feature` files for traceability or to read `TECH_DEBT.md`, and `work-loops-coverage-ledger` never
  calls `loadLoops` at all. Their content pins are untouched: the census still asserts the roster is
  the named nine as an EQUALITY (`:514-518`), records-parse still asserts it as a FLOOR (`:36`), and
  both keep every field, cadence and pointer assertion they carry today.

  One assertion in a fixture suite is genuinely hard-coded to the old shape and must move with the
  home: `test/work-loops-record.test.mjs:364`, `assert.equal(absent.source, path.join(fixture.workDir,
  "loops"))`. It survives the string overload (task 00) unchanged in VALUE — the fixture passes a temp
  base — so it is re-read here to confirm it still asserts what it means to. ADR-012 §6–§7.

  Scenario: there is exactly one source of truth for a loop record
    Given the repository after this story
    Then `src/bundle/loops/` holds nine records
    And `wiki/work/loops/` does not exist
    And no record's content is authored in two places
    And the move is a `git mv`, so each record's history follows it

  Scenario: this repo's `.aof/loops/` is installed, not authored
    Given `.aof/loops/` in this repository
    Then each of its nine files is byte-identical to its `src/bundle/loops/` counterpart
    And each is tracked by git, exactly as `.aof/templates/` is
    And running `aof work update` in this repository plans `skip` for all nine
    And a record corrected in `src/bundle/loops/` and not re-installed is caught, rather than silently read as current

  Scenario: the dogfood is only evidence if the halves are pinned equal
    Given a record edited under `.aof/loops/` but not under `src/bundle/loops/`
    When the equality is checked
    Then it fails and names the record
    And the failure says which half is stale
    And this is the leg that stops the two real-registry suites reading a subject that no longer ships

  Scenario: the equality is against the SOURCE bytes, never against the manifest's hashes
    Given a record corrected in `src/bundle/loops/` whose manifest entry has not been regenerated
    And an installed copy that still matches the stale manifest entry
    When the byte-equality leg runs
    Then it FAILS, because the installed copy does not match the source file
    And it would have PASSED had it compared against the manifest, which is why it does not
    And the manifest comparison is kept as a separate, independent leg rather than as this one's referent

  Scenario: the census suite reads the installed registry and still pins the named nine
    Given `test/work-loops-registry-census.test.mjs`
    When its work root is resolved
    Then it resolves `<root>/.aof` rather than `<root>/wiki/work`
    And the roster equality still asserts nine nodes — seven loops, two actors
    And the day-one loop ids and actor ids are unchanged
    And the warn-lane census, the declared edges, the six event cadences and the `prose:` path checks are unchanged

  Scenario: the parse arch-test reads the installed registry and still pins the floor
    Given `test/arch/acd-loop-records-parse.test.mjs`
    When each of its two loads is resolved
    Then both resolve `<root>/.aof`
    And the roster floor of at least nine still holds
    And zero error-severity findings still holds
    And every `command:` pointer still resolves against the command registry
    And every `module:` pointer's operand file is still read from the repo root and must declare its symbol

  Scenario: the five suites the STORY miscounted are not edited for the home
    Given `work-loops-record`, `work-loops-value`, `work-loops-checks`, `work-loops-commands` and `work-loops-coverage-ledger`
    Then none of them loads the live registry
    And their `wiki/work/...` references are `.feature` and ledger paths, which do not move
    And no repoint edit is made to any of them for the home change

  Scenario: the one hard-coded fixture path assertion still asserts what it means
    Given `test/work-loops-record.test.mjs`'s absent-registry case
    When the loader is handed the fixture's temp base
    Then the reported `source` is the fixture's own loops directory
    And the assertion is re-read against the string overload rather than left to pass by coincidence

  Scenario: the reads-only-the-registry case is re-read, and needs no edit
    Given the value suite's case that plants files around the registry to prove nothing outside it is consulted
    When it is read after the home change
    Then it already plants an `.aof/aof.config.json` at each of its three roots
    And the fixture's parent chain does not move, because the fixture reaches the loader through the string overload
    And it is therefore confirmed unchanged rather than edited — the earlier reading that it needed a new member was wrong

  Scenario: `wiki/work/` loses its only non-item directory
    Given the work stream after this story
    Then it holds no `loops/` directory
    And 52/ADR-001's "first non-item directory in `work.dir`" cost is discharged rather than inherited
    And 52/ADR-001 decision 3 — one directory, extended by `kind:`, never by a sibling — carries over to the new home unchanged

  Examples:
    | file                                           | today                              | after                        |
    | `test/work-loops-registry-census.test.mjs:60`  | `path.join(root, "wiki", "work")`  | `path.join(root, ".aof")`    |
    | `test/work-loops-registry-census.test.mjs:4`   | header names `wiki/work/loops/`    | names `.aof/loops/`          |
    | `test/arch/acd-loop-records-parse.test.mjs:29` | `path.join(root, "wiki/work")`     | `path.join(root, ".aof")`    |
    | `test/arch/acd-loop-records-parse.test.mjs:80` | `path.join(root, "wiki/work")`     | `path.join(root, ".aof")`    |
    | `test/arch/acd-loop-records-parse.test.mjs:69` | comment names `wiki/work/loops/`   | names `.aof/loops/`          |
    | `test/work-loops-record.test.mjs`              | fixture temp base                  | unchanged                    |
    | `test/work-loops-value.test.mjs`               | fixture temp base                  | unchanged                    |
    | `test/work-loops-checks.test.mjs`              | literals, never touches disk       | unchanged                    |
    | `test/work-loops-commands.test.mjs`            | fixture + spawned CLI              | the synthetic workspace and the fixture parent (task 00) |
    | `test/work-loops-coverage-ledger.test.mjs`     | never loads a registry             | unchanged                    |
    | `test/support/loop-registry-fixture.mjs`       | `path.join(workDir, "loops")`      | one defaulted `parent` parameter; no `loadLoops(` call site moves |

  Examples:
    | half                     | role                        | who writes it            |
    | `src/bundle/loops/*.md`  | the single source of truth  | a human, in a PR         |
    | `.aof/loops/*.md` (here) | an installed artifact       | `aof work update`        |
    | `.aof/loops/*.md` (consumer) | an installed artifact   | `aof work init`/`update` |
    | `wiki/work/loops/`       | gone                        | nobody                   |
