@manual @cli @work @work-stream
Feature: aof work archive --done moves every accepted driver of this repository under wiki/work/archive/, name verbatim, and the operator records the move as renames, four hand-fixed links and one regenerated index

  Measured on 2026-09-15 at this refine: the stream root holds 130 numbered folders — 125
  `done` drivers, three `in-progress` milestones (`127`, `129`, `130`), one `blocked` uat
  (`32`) — plus `42_structural-overhaul`, an imported folder no `ITEM_RE` matches (it has no
  type segment; the scanner ignores it as it ignores `TECH_DEBT.md`, and so does the verb). The
  SPEC's framing count of 123 has moved by two accepts since. This task is the one act the
  milestone exists for, done ONCE, for real, by the developer at the build and recorded as
  evidence; its post-state is task 02's `@executable` contract over the real tree. It is
  `@manual` because it writes the operator's checkout — 125 folder renames and the link
  rewrites 03/01 specifies — and because its evidence is `git status`, which no fixture can
  stand in for.

  THE ACT, in order, on the milestone branch, on a checkout whose `git status` is clean apart
  from this story's own files (other lanes edit this tree mid-session — gate on the item ref,
  read `git status` BEFORE and AFTER, never `git add -A`):
    (1) `aof work archive --done --json` WITHOUT `--yes` — the verb lists its candidates behind
        the confirm gate (`archive-confirm-required`, `candidates` in `detail`, 03/02) and moves
        nothing; the list is 125 refs, every one `status: done`, none of `127`, `129`, `130`,
        `32`, and recorded verbatim in `VERIFICATION.md`;
    (2) `aof work archive --done --yes --json` — the move; the envelope's `archived` has 125
        entries in number order and `rewritten` names every file whose links crossed the line;
    (3) stage EXACTLY the paths the envelope names — `git add -- wiki/work/archive` plus each
        `from` path and each `rewritten` path, never `-A` — then `git status --porcelain`: git
        pairs a staged delete with a staged add of the same bytes, so every moved folder
        reports as renames (`R`), the rewritten files as modifications (`M`), and NOTHING
        else is staged or changed: no `number:` line anywhere, no frontmatter reserialised, no
        `updated:` bumped (03/00 — `git diff --cached` over the moved record docs is empty
        apart from link lines). An unstaged move reads as `D` + `??`, which is not evidence;
    (4) the FOUR LINKS OUTSIDE `wiki/work` — 03/01 measured zero files outside the work dir
        linking into an item folder and the verb therefore touches none; re-measured at this
        refine there are four, all in `wiki/memory.md` (`work/05_milestone_work-memory/…`, lines
        15, 130, 137, 147), and `05` is `done`. They are fixed BY HAND in this story to
        `work/archive/05_milestone_work-memory/…` — a docs edit, declared in `files:`. The three
        `wiki/planning/PRD-command-spine-effects-ledger.md` links into `42_structural-overhaul`
        point at a folder that does not move and stay as they are;
    (5) `aof work memory ingest` — the memory index (`.aof/aof.memory.graphify.index.json`,
        gitignored) is regenerated by the existing verb, which is how ADR-004 §4 says the index
        follows a move; `archive` itself ran no ingest;
    (6) the ledger: STORY.md's brief named "the `TECH_DEBT.md` entries this milestone discharges
        (the three `ITEM_RE` homes, the seven scanners)" for deletion. Re-measured at this
        refine there is NO such entry — the SPEC described a debt the tree carried in code,
        never one the ledger recorded — so there is nothing to delete, and this is ratified in
        this beat. The ledger's only change is the crossing-link rewrite the verb performs on
        it (a root-level file, 03/01 rule (ii)); `aof work debt --json`'s findings are the same
        set before and after.

  What would quietly undo this: running the move with a dirty tree and committing another
  lane's edits as renames; `git add -A`; a hand-fix of `wiki/memory.md` that also "tidies" a
  sentence; archiving `32` because it is old (it is `blocked`, not `done` — a status question,
  SPEC out-of-scope); running the act in a worktree lane whose `cd` persisted (dispatch
  worktrees mirror `wiki/work`, and a move there is a move of the wrong tree).

  ADR-004 §1, §2, §4; ADR-002 §3; 03/00, 03/01, 03/02; SPEC §Objective; STATE (the "Open for 05"
  note — the retired `.mjs` suites under `35_…/reference/` keep a relative `import` that breaks
  after the move; accepted, they are in no runner).

  Scenario: the candidate list is every done driver and nothing live
    Given the milestone branch checked out clean at the repository root, stories 01–04 accepted, and `git status --porcelain` recorded
    When `aof work archive --done --json` runs without `--yes`
    Then it is refused as `archive-confirm-required` with 125 candidates, each `status: done`, none of `127`, `129`, `130` or `32`, and `42_structural-overhaul` absent from the list
    And `git status --porcelain` is byte-identical to the recording — nothing moved
    And the candidate list is recorded in the milestone `VERIFICATION.md` under `127/05`

  Scenario: the move is 125 renames, the crossing links, and nothing else
    Given the same checkout
    When `aof work archive --done --yes --json` runs
    Then the envelope's `archived` holds 125 entries in number order, `from` at the root and `to` under `wiki/work/archive/`, and `rewritten` lists every file with a crossing link and its count
    And after staging exactly the envelope's paths (never `git add -A`), `git status --porcelain` reports every entry of `archived` as renames (`R`) of its folder's files, every entry of `rewritten` as a modification (`M`), and no other path
    And `git diff --cached` over every moved record doc shows changed lines that are link lines only — no `number:`, no `status:`, no `updated:`, no frontmatter delimiter
    And `ls wiki/work` is exactly: `127_milestone_backlog-and-archive`, `129_milestone_loop-concurrency`, `130_milestone_stop-a-running-loop`, `32_uat_whole-mesh-acceptance`, `42_structural-overhaul`, `ROADMAP.md`, `TECH_DEBT.md`, `loops.md`, `archive`, `backlog`
    And the envelope and the `git status` are recorded in `VERIFICATION.md` under `127/05`

  Scenario: the four links outside the work dir are fixed by hand, and the ledger loses no entry
    Given the moved tree
    When `wiki/memory.md` is edited
    Then its four links into `work/05_milestone_work-memory/…` read `work/archive/05_milestone_work-memory/…` and each resolves to an existing file; `git diff wiki/memory.md` is exactly those four lines
    And `grep -rnE "\]\([^)]*work/[0-9]+_" wiki --include=*.md` outside `wiki/work/` finds only the three `wiki/planning/…` links into `42_structural-overhaul`, which resolve as before
    And `aof work debt --json` reports the same `findings` set as before the move, and `wiki/work/TECH_DEBT.md`'s diff is link rewrites only

  Scenario: the memory index is regenerated by the existing verb and answers for an archived milestone
    Given the moved tree
    When `aof work memory ingest` runs from the repository root
    Then it reports the records re-indexed, and `aof work memory recall "loop registry" --item 52 --json` answers at least one record whose `source` resolves to a file under `wiki/work/archive/52_milestone_loop-registry-and-graph/`
    And the count of records re-indexed is recorded in `VERIFICATION.md` beside the pre-move count from 127/01's accept (2,341)
