@executable @docs @work @planning
Feature: the architect's ADR rule and refine's Decide stage carry one diagram step, which names aof's verbs and never a generator

  WHY. SPEC: "The architect draws at refine … The judgement 'does this need a diagram?' is the
  architect's, stated in the ADR. Not every ADR gets one." And: "Changing `work.diagrams` in config
  (or turning it off) changes what refine does, with no edit to the bundle prose." ADR-008 meets
  both by giving the prose ONE step that asks `aof diagram plan` and follows the answer. The prose
  never decides whether drawing is on and never names the tool. The step EXTENDS the ADR
  authoring the two documents already describe. It is not a sibling section beside it.

  RULINGS (QA, 2026-09-23).
  (1) This suite reads the bundle SOURCE (`src/bundle/agents/aof-architect.md`,
      `src/bundle/commands/refine.md`) and the six rendered copies. It pins the step's content
      (the brief, the three branches, the two verbs, solo mode), not its wording.
  (2) "One step" is measured: in each source document, `aof diagram plan` appears inside exactly one
      contiguous passage, and that passage sits inside the section that already describes ADR
      authoring (the architect's responsibilities list; refine's Decide stage).
  (3) No bundle document names the generator. FF-13301 enforces that for `src/**`. This task also
      checks the rendered copies, which sit outside `src/`.
  (4) The rendered copies are regenerated by `aof work update` in this change. Each copy must equal
      what a fresh render of the source produces, which is the existing bundle-drift discipline, so
      no copy is hand-edited.
  (5) `.aof/aof.lock.json` changes with the render and is committed by hand on the lane branch
      (memory `lane-commits-drop-aof-config`). That is a delivery step, not a scenario.

  Background:
    Given the bundle source and its rendered copies are read from this checkout

  Scenario Outline: the step is in both source documents, inside the ADR authoring they already describe
    When <document> is read
    Then it contains one passage that names `aof diagram plan` and `aof diagram export`
    And that passage sits inside <section>

    Examples:
      | document                             | section                                                        |
      | `src/bundle/agents/aof-architect.md` | the section listing what the architect writes, beside the ADR bullet |
      | `src/bundle/commands/refine.md`      | the milestone Decide step, beside `aof-architect` → ADRs         |

  Scenario Outline: the step states the judgement, the brief and each branch
    When the diagram passage of <document> is read
    Then it says a diagram is drawn only for an ADR whose design has moving parts, that most ADRs get none, and that the judgement is the architect's
    And it says to write the ADR's `### Diagram` brief (why a picture helps, the view, the components, the flows) before asking
    And it gives the command `aof diagram plan <ref> <ADR-NNN> --slug <slug> --json`
    And it says that `enabled: false` means drop the brief and record nothing
    And it says that `available: false` means keep the brief, record `diagram not drawn: <code>` in `STATE.md`, and continue, and that this is never a stop
    And it says that otherwise the drawing agent follows the answer's `instructions`, then runs `aof diagram export <ref> <ADR-NNN> --json` and pastes the returned `block` under the brief
    And it says aof never edits `ARCHITECTURE.md`, because the architect pastes the block

    Examples:
      | document                             |
      | `src/bundle/agents/aof-architect.md` |
      | `src/bundle/commands/refine.md`      |

  Scenario: refine says the main session runs the step itself in solo mode
    When the diagram passage of `src/bundle/commands/refine.md` is read
    Then it says that on a solo refine the main session is the architect and runs the same step

  Scenario Outline: no bundle document names the generator
    When <document> is read with its comments kept
    Then it does not contain the text `diagram-design`
    And it does not contain `/diagram-design:`

    Examples:
      | document                                |
      | `src/bundle/agents/aof-architect.md`    |
      | `src/bundle/commands/refine.md`         |
      | `.claude/agents/aof-architect.md`       |
      | `.claude/commands/aof/refine.md`        |
      | `.codex/agents/aof-architect.md`        |
      | `.codex/skills/aof-refine/SKILL.md`     |
      | `.opencode/agents/aof-architect.md`     |
      | `.opencode/commands/aof/refine.md`      |

  Scenario Outline: every rendered copy carries the step and matches a fresh render
    When <copy> is read
    Then it contains the diagram passage's command `aof diagram plan <ref> <ADR-NNN> --slug <slug> --json`
    And it is byte-identical to what `aof work update` renders from the current source

    Examples:
      | copy                                    |
      | `.claude/agents/aof-architect.md`       |
      | `.claude/commands/aof/refine.md`        |
      | `.codex/agents/aof-architect.md`        |
      | `.codex/skills/aof-refine/SKILL.md`     |
      | `.opencode/agents/aof-architect.md`     |
      | `.opencode/commands/aof/refine.md`      |

  Scenario: the architect's tools are not widened to draw
    When `src/bundle/frozen-set.jsonc` is read
    Then the architect's tools are still exactly `Read, Grep, Glob, Bash, Write, Edit`
    And `src/bundle/agents/aof-architect.md` does not ask for the `Skill` tool

  Scenario: the commands the prose names are the commands that exist
    When `aof diagram plan` and `aof diagram export` are looked up in the command registry
    Then each resolves to a registered command, `diagram:plan` and `diagram:export`
    And every flag the passage passes to them (`--slug`, `--json`) is one the command accepts
