// Compatibility entry; construction belongs to core application assembly.
import { workMemory } from "../application/default.mjs";
export const {
  MEMORY_VERBS,
  SCOPE_FLAGS,
  BACKEND_REGISTRY,
  selectBackendName,
  declaredBackendName,
  MEMORY_BACKEND_CONFIG_PATH,
  applyDefaultBackendSelection,
  resolveConfiguredBackend,
  parseMemoryArgv,
  HOOK_LIMIT,
  renderRecallBlock,
  renderMemory,
  memoryJson,
  briefDigest,
  MEMORY_USAGE,
  memoryUsage,
  memoryHelpRequested,
  memoryVerbRefusal,
  gateMemoryVerb,
  executeMemoryVerb,
  runMemoryVerb,
  runMemory,
} = workMemory;
