// Compatibility entry; construction belongs to core application assembly.
import { meshWorktree } from "../application/default.mjs";
export const {
  DEFAULT_WORKTREE_RETENTION_MS,
  WORKTREE_PREPARE_DEADLINE_EXPIRED,
  WORKTREE_PREPARE_FAILED,
  WORKTREE_PREPARE_NOT_STARTED,
  addDispatchWorktree,
  addSessionWorktree,
  addWorktree,
  adoptRemoteBranch,
  advanceBranchToBase,
  commitWorktreeChanges,
  defaultGitExec,
  dispatchWorktreeSlug,
  ensureCommitAvailable,
  findItemWorktree,
  headCommit,
  isInsideMeshWorktree,
  isUnderMeshDispatchWorktreesRoot,
  isUnderMeshSessionWorktreesRoot,
  isUnderMeshWorktreesRoot,
  listWorktrees,
  localBranchExists,
  meshDispatchWorktreePath,
  meshDispatchWorktreesRoot,
  meshIdentityArgs,
  meshItemBranchName,
  meshSessionWorktreePath,
  meshSessionWorktreesRoot,
  meshWorktreePath,
  meshWorktreesRoot,
  parsePorcelainStatus,
  remoteBranchExists,
  removeDispatchWorktree,
  removeWorktree,
  resolveExec,
  reuseWorktreeOnBranch,
  sessionWorktreeSlug,
  sweepRetainedWorktrees,
} = meshWorktree;
