// Explicit first-party construction order. No factory receives the whole application.
import { createBaseServices } from './base.mjs';
import { createApplicationLifetime } from './lifetime.mjs';
import { assembleGlobalWorkStore } from './bindings/global-work-store.mjs';
import { assembleBoardMeshExecution } from './bindings/board-mesh-execution.mjs';
import { assembleDsl } from './bindings/dsl.mjs';
import { assembleConfigInspect } from './bindings/config-inspect.mjs';
import { assembleConfigEditor } from './bindings/config-editor.mjs';
import { assembleBoardUi } from './bindings/board-ui.mjs';
import { assembleTerminalSessions } from './bindings/terminal-sessions.mjs';
import { assembleTerminalWs } from './bindings/terminal-ws.mjs';
import { assembleSetupUi } from './bindings/setup-ui.mjs';
import { assembleBoardServe } from './bindings/board-serve.mjs';
import { assembleCacheRead } from './bindings/cache-read.mjs';
import { assembleWorkLoops } from './bindings/work/loops.mjs';
import { assembleWorkAcceptorCriterion } from './bindings/work-acceptor/criterion.mjs';
import { assembleMeshWorktree } from './bindings/mesh/worktree.mjs';
import { assembleEffectsJournal } from './bindings/effects/journal.mjs';
import { assembleWorkAcceptorObservations } from './bindings/work-acceptor/observations.mjs';
import { assembleEffectsTable } from './bindings/effects/table.mjs';
import { assembleEffectsDispatch } from './bindings/effects/dispatch.mjs';
import { assembleWorkAcceptorStore } from './bindings/work-acceptor/store.mjs';
import { assembleEffectsHarnessTransitions } from './bindings/effects/harness-transitions.mjs';
import { assembleCommandsAcceptor } from './bindings/commands/acceptor.mjs';
import { assembleRunStore } from './bindings/run-store.mjs';
import { assembleWorkContentRead } from './bindings/work/content-read.mjs';
import { assembleLoopStopRequest } from './bindings/loop/stop-request.mjs';
import { assembleMeshPresence } from './bindings/mesh/presence.mjs';
import { assembleGlobalNodeRegistry } from './bindings/global-node-registry.mjs';
import { assembleGlobalWorkPublisher } from './bindings/global-work-publisher.mjs';
import { assembleItemLock } from './bindings/item-lock.mjs';
import { assembleEffectsStreamTransitions } from './bindings/effects/stream-transitions.mjs';
import { assembleCommandsArchive } from './bindings/commands/archive.mjs';
import { assembleWorkAuditCensus } from './bindings/work-audit/census.mjs';
import { assembleWorkAuditEvidence } from './bindings/work-audit/evidence.mjs';
import { assembleWorkAuditPromptLayer } from './bindings/work-audit/prompt-layer.mjs';
import { assembleWorkAuditSeamLiveness } from './bindings/work-audit/seam-liveness.mjs';
import { assembleWorkAuditDeclaredBounds } from './bindings/work-audit/declared-bounds.mjs';
import { assembleWorkAuditReport } from './bindings/work-audit/report.mjs';
import { assembleCommandsAudit } from './bindings/commands/audit.mjs';
import { assembleWorkRead } from './bindings/work/read.mjs';
import { assembleEffectsOutbox } from './bindings/effects/outbox.mjs';
import { assembleEffectsAssignmentTransitions } from './bindings/effects/assignment-transitions.mjs';
import { assembleMeshAssignment } from './bindings/mesh/assignment.mjs';
import { assembleCommandsResolve } from './bindings/commands/resolve.mjs';
import { assembleEffectsItemTransitions } from './bindings/effects/item-transitions.mjs';
import { assembleCommandsContinue } from './bindings/commands/continue.mjs';
import { assembleRunHeartbeatConsumption } from './bindings/run-heartbeat-consumption.mjs';
import { assembleEffectsRunTransitions } from './bindings/effects/run-transitions.mjs';
import { assembleCommandsRunRetry } from './bindings/commands/run-retry.mjs';
import { assembleCommandsCounters } from './bindings/commands/counters.mjs';
import { assembleDiagramsRasterize } from './bindings/diagrams/rasterize.mjs';
import { assembleCommandsDiagramExport } from './bindings/commands/diagram/export.mjs';
import { assembleCommandsDiagramFile } from './bindings/commands/diagram/file.mjs';
import { assembleCommandsDiagramPlan } from './bindings/commands/diagram/plan.mjs';
import { assembleMeshLauncherLock } from './bindings/mesh/launcher-lock.mjs';
import { assembleWorkDispatch } from './bindings/work/dispatch.mjs';
import { assembleCommandsDispatch } from './bindings/commands/dispatch.mjs';
import { assembleCommandsDoc } from './bindings/commands/doc.mjs';
import { assembleWorkDoctorDiagrams } from './bindings/work/doctor-diagrams.mjs';
import { assembleWorkDoctor } from './bindings/work/doctor.mjs';
import { assembleEffectsReconcile } from './bindings/effects/reconcile.mjs';
import { assembleCommandsDoctor } from './bindings/commands/doctor.mjs';
import { assembleLoopAskRequest } from './bindings/loop/ask-request.mjs';
import { assembleRunSessionCapture } from './bindings/run-session-capture.mjs';
import { assembleRunSpendIngest } from './bindings/run-spend-ingest.mjs';
import { assembleCommandsDrive } from './bindings/commands/drive.mjs';
import { assembleEffectsDocTransitions } from './bindings/effects/doc-transitions.mjs';
import { assembleCommandsFeedback } from './bindings/commands/feedback.mjs';
import { assembleCommandsFind } from './bindings/commands/find.mjs';
import { assembleCommandsGrade } from './bindings/commands/grade.mjs';
import { assembleGraphify } from './bindings/graphify.mjs';
import { assembleCommandsGraphBuild } from './bindings/commands/graph/build.mjs';
import { assembleCommandsGraphQuery } from './bindings/commands/graph/query.mjs';
import { assembleGraphMcpServer } from './bindings/graph-mcp-server.mjs';
import { assembleCommandsGraphServe } from './bindings/commands/graph/serve.mjs';
import { assembleCommandsGraphTriage } from './bindings/commands/graph/triage.mjs';
import { assembleImportStore } from './bindings/import/store.mjs';
import { assembleImportRecovery } from './bindings/import/recovery.mjs';
import { assembleImportMaterialize } from './bindings/import/materialize.mjs';
import { assembleWorkMemory } from './bindings/work/memory.mjs';
import { assembleCommandsImportMilestone } from './bindings/commands/import-milestone.mjs';
import { assembleCommandsInsertShared } from './bindings/commands/insert-shared.mjs';
import { assembleCommandsPromote } from './bindings/commands/promote.mjs';
import { assembleCommandsInsertChore } from './bindings/commands/insert-chore.mjs';
import { assembleCommandsInsertMilestone } from './bindings/commands/insert-milestone.mjs';
import { assembleCommandsInsertStory } from './bindings/commands/insert-story.mjs';
import { assembleCommandsInsertUat } from './bindings/commands/insert-uat.mjs';
import { assembleNotifySecret } from './bindings/notify/secret.mjs';
import { assembleNotifyAskMessages } from './bindings/notify/ask-messages.mjs';
import { assembleNotifyNotify } from './bindings/notify/notify.mjs';
import { assembleCommandsItemStatus } from './bindings/commands/item-status.mjs';
import { assembleCommandsList } from './bindings/commands/list.mjs';
import { assembleCommandsLoopDocument } from './bindings/commands/loop-document.mjs';
import { assembleCommandsLoopRecord } from './bindings/commands/loop-record.mjs';
import { assembleLoopProgress } from './bindings/loop-progress.mjs';
import { assembleLoopChildDrive } from './bindings/loop/child-drive.mjs';
import { assembleLoopAsk } from './bindings/loop/ask.mjs';
import { assembleLoopCycle } from './bindings/loop/cycle.mjs';
import { assembleLoopWave } from './bindings/loop/wave.mjs';
import { assembleLoopDiag } from './bindings/loop-diag.mjs';
import { assembleLoopStop } from './bindings/loop/stop.mjs';
import { assembleCommandsLoop } from './bindings/commands/loop.mjs';
import { assembleCommandsLoopsGraph } from './bindings/commands/loops-graph.mjs';
import { assembleCommandsLoopsGroundedness } from './bindings/commands/loops-groundedness.mjs';
import { assembleCommandsLoopsShow } from './bindings/commands/loops-show.mjs';
import { assembleCommandsLoopsValidate } from './bindings/commands/loops-validate.mjs';
import { assembleCommandsMeshAssign } from './bindings/commands/mesh/assign.mjs';
import { assembleMeshRegistry } from './bindings/mesh/registry.mjs';
import { assembleCommandsMeshIdentity } from './bindings/commands/mesh/identity.mjs';
import { assembleCommandsMeshHeartbeat } from './bindings/commands/mesh/heartbeat.mjs';
import { assembleMeshRelay } from './bindings/mesh/relay.mjs';
import { assembleCommandsMeshRelay } from './bindings/commands/mesh/relay.mjs';
import { assembleCommandsMeshInvite } from './bindings/commands/mesh/invite.mjs';
import { assembleCommandsMeshJoin } from './bindings/commands/mesh/join.mjs';
import { assembleCommandsMeshRevoke } from './bindings/commands/mesh/revoke.mjs';
import { assembleMeshTerminalRelayBridge } from './bindings/mesh/terminal-relay-bridge.mjs';
import { assembleMeshRecoveryPush } from './bindings/mesh/recovery-push.mjs';
import { assembleMeshResync } from './bindings/mesh/resync.mjs';
import { assembleWorkerStreamClient } from './bindings/worker-stream-client.mjs';
import { assembleMeshRelayClient } from './bindings/mesh/relay-client.mjs';
import { assembleControlStreamServer } from './bindings/control-stream-server.mjs';
import { assembleMeshParkResume } from './bindings/mesh/park-resume.mjs';
import { assembleMeshWorkerLaunch } from './bindings/mesh/worker-launch.mjs';
import { assembleMeshWorkerRepoAdmission } from './bindings/mesh/worker-repo-admission.mjs';
import { assembleMeshWorkerExecution } from './bindings/mesh/worker-execution.mjs';
import { assembleMeshSessionSpawnHandler } from './bindings/mesh/session-spawn-handler.mjs';
import { assembleMeshTerminalMirror } from './bindings/mesh/terminal-mirror.mjs';
import { assembleMeshTerminalInput } from './bindings/mesh/terminal-input.mjs';
import { assembleMeshAssignmentReclaim } from './bindings/mesh/assignment-reclaim.mjs';
import { assembleMeshCloneCredentialProvider } from './bindings/mesh/clone-credential-provider.mjs';
import { assembleMeshLauncher } from './bindings/mesh/launcher.mjs';
import { assembleCommandsMeshServe } from './bindings/commands/mesh/serve.mjs';
import { assembleCommandsMeshLogs } from './bindings/commands/mesh/logs.mjs';
import { assembleCommandsMeshTerminalResume } from './bindings/commands/mesh/terminal-resume.mjs';
import { assembleCommandsMeshRecoverPush } from './bindings/commands/mesh/recover-push.mjs';
import { assembleCommandsMeshRepo } from './bindings/commands/mesh/repo.mjs';
import { assembleGlobalMeshQuery } from './bindings/global-mesh-query.mjs';
import { assembleMeshUiServe } from './bindings/mesh/ui-serve.mjs';
import { assembleCommandsMeshUi } from './bindings/commands/mesh/ui.mjs';
import { assembleCommandsMeshDesktopPreflight } from './bindings/commands/mesh/desktop-preflight.mjs';
import { assembleCommandsMeshDesktop } from './bindings/commands/mesh/desktop.mjs';
import { assembleCommandsMeshContribution } from './bindings/commands/mesh/contribution.mjs';
import { assembleCommandsMessagingMessaging } from './bindings/commands/messaging/messaging.mjs';
import { assembleCommandsMigrateFolder } from './bindings/commands/migrate-folder.mjs';
import { assembleCommandsNext } from './bindings/commands/next.mjs';
import { assembleIntegrationsRouting } from './bindings/integrations/routing.mjs';
import { assembleCommandsNotionAssociate } from './bindings/commands/notion-associate.mjs';
import { assembleNotionMapping } from './bindings/notion/mapping.mjs';
import { assembleNotionSync } from './bindings/notion/sync.mjs';
import { assembleNotionCli } from './bindings/notion/cli.mjs';
import { assembleNotionSyncWork } from './bindings/notion/sync-work.mjs';
import { assembleCommandsNotionSyncWork } from './bindings/commands/notion-sync-work.mjs';
import { assembleCommandsObserve } from './bindings/commands/observe.mjs';
import { assembleCommandsPromoteFindingToChore } from './bindings/commands/promote-finding-to-chore.mjs';
import { assembleCommandsPromoteGapToChore } from './bindings/commands/promote-gap-to-chore.mjs';
import { assembleCommandsRatchet } from './bindings/commands/ratchet.mjs';
import { assembleWorkTestSelect } from './bindings/work/test-select.mjs';
import { assembleWorkTestChanged } from './bindings/work/test-changed.mjs';
import { assembleWorkToolchain } from './bindings/work/toolchain.mjs';
import { assembleCommandsTest } from './bindings/commands/test.mjs';
import { assembleCommandsRegressionGate } from './bindings/commands/regression-gate.mjs';
import { assembleCommandsResume } from './bindings/commands/resume.mjs';
import { assembleCommandsResync } from './bindings/commands/resync.mjs';
import { assembleCommandsRunComplete } from './bindings/commands/run-complete.mjs';
import { assembleCommandsRunStart } from './bindings/commands/run-start.mjs';
import { assembleCommandsRunStatus } from './bindings/commands/run-status.mjs';
import { assembleCommandsTasks } from './bindings/commands/tasks.mjs';
import { assembleWorkTriggerDeclaration } from './bindings/work-trigger/declaration.mjs';
import { assembleCommandsTrigger } from './bindings/commands/trigger.mjs';
import { assembleMemoryLocalIndexing } from './bindings/memory/local-indexing.mjs';
import { assembleWorkTuneCorpus } from './bindings/work-tune/corpus.mjs';
import { assembleWorkTuneProposal } from './bindings/work-tune/proposal.mjs';
import { assembleCommandsTune } from './bindings/commands/tune.mjs';
import { assembleWorkUpgrade } from './bindings/work/upgrade.mjs';
import { assembleCommandsUpgrade } from './bindings/commands/upgrade.mjs';
import { assembleCommandsValidate } from './bindings/commands/validate.mjs';
import { assembleCommandsWorkMemory } from './bindings/commands/work/memory.mjs';
import { assembleCommandsWorkUi } from './bindings/commands/work-ui.mjs';
import { assembleDiscordCommands } from './bindings/discord/commands.mjs';
import { assembleDiscordGateway } from './bindings/discord/gateway.mjs';
import { assembleDiscordReplies } from './bindings/discord/replies.mjs';
import { assembleDiscordBot } from './bindings/discord/bot.mjs';
import { assembleMemoryGraphifyBackend } from './bindings/memory/graphify-backend.mjs';
import { assembleMemoryLocalBackend } from './bindings/memory/local-backend.mjs';
import { assembleMeshDeclarations } from './bindings/mesh/declarations.mjs';
import { assembleStoryContractDerive } from './bindings/story-contract-derive.mjs';
import { assembleWorkExamplesAnswers } from './bindings/work-examples/answers.mjs';
import { assembleWorkInit } from './bindings/work/init.mjs';
import { assembleCommandsInitUpdate } from './bindings/commands/init-update.mjs';
import { assembleCommandsAssetsUi } from './bindings/commands/assets/ui.mjs';
import { assembleSpineFace } from './bindings/spine/face.mjs';
import { assembleScaffold } from './bindings/scaffold.mjs';
import { assembleCommandsAssetsShow } from './bindings/commands/assets/show.mjs';
import { assembleCommandsAssetsRemove } from './bindings/commands/assets/remove.mjs';
import { assembleCommandsAssetsAdd } from './bindings/commands/assets/add.mjs';
import { assembleCommandsValidateShared } from './bindings/commands/validate-shared.mjs';
import { assembleCommandsAssetsApply } from './bindings/commands/assets/apply.mjs';
import { assembleCommandsAssetsList } from './bindings/commands/assets/list.mjs';
import { assembleCommandsAssetsRefs } from './bindings/commands/assets/refs.mjs';
import { assembleCommandsPackagesInstall } from './bindings/commands/packages-install.mjs';
import { assembleCommandsPackagesList } from './bindings/commands/packages-list.mjs';
import { assembleCommandsPackagesShow } from './bindings/commands/packages-show.mjs';
import { assembleCommandsProjectDoctor } from './bindings/commands/project-doctor.mjs';
import { assembleWorkspaceWriter } from './bindings/workspace-writer.mjs';
import { assembleCommandsProjectMigrate } from './bindings/commands/project-migrate.mjs';
import { assembleCommandsProjectShow } from './bindings/commands/project-show.mjs';
import { assembleSync } from './bindings/sync.mjs';
import { assembleCommandsAssetsValidate } from './bindings/commands/assets/validate.mjs';
import { assembleCommandsPackagesValidate } from './bindings/commands/packages-validate.mjs';
import { assembleCommandsProjectInit } from './bindings/commands/project-init.mjs';
import { assembleCommandsProjectValidate } from './bindings/commands/project-validate.mjs';
import { assembleCommandCore } from './bindings/command-core.mjs';

export function assembleApplication({ env = process.env, base = createBaseServices({ env }) } = {}) {
  const lifetime = createApplicationLifetime();
  const { workspace, diagnosticsLog, degrade, claudeTrust, workObserve, terminalProviders, terminalScreen, terminalSessionScreen, agentSessionDriver, fs, workDigestTemplate, work, meshStore, meshSession, commandsMeshSession } = base;
  // Transports and recursive work operations may invoke the registry after registration.
  const commandPort = {
    invoke: (...args) => { lifetime.assertReady(); return commandCore.invoke(...args); },
    getCommand: (...args) => { lifetime.assertReady(); return commandCore.getCommand(...args); },
    listCommands: (...args) => { lifetime.assertReady(); return commandCore.listCommands(...args); },
    loadWorkspace: (...args) => { lifetime.assertReady(); return work.loadWorkspace(...args); },
  };
  const globalWorkStore = assembleGlobalWorkStore({ workspaceServices: workspace, workServices: work, degradeServices: degrade });
  globalWorkStore.openGlobalWorkProjectionStore = lifetime.open(globalWorkStore.openGlobalWorkProjectionStore);
  const boardMeshExecution = assembleBoardMeshExecution({ globalWorkStoreServices: globalWorkStore, workspaceServices: workspace, degradeServices: degrade });
  const dsl = assembleDsl({ fsServices: fs, workspaceServices: workspace });
  const configInspect = assembleConfigInspect({ dslServices: dsl, fsServices: fs, workspaceServices: workspace, degradeServices: degrade });
  const configEditor = assembleConfigEditor({ configInspectServices: configInspect, dslServices: dsl, fsServices: fs, workspaceServices: workspace });
  const boardUi = assembleBoardUi({ commandCoreServices: commandPort });
  const terminalSessions = assembleTerminalSessions({ degradeServices: degrade });
  const terminalWs = assembleTerminalWs({ workServices: work, claudeTrustServices: claudeTrust, terminalProvidersServices: terminalProviders, terminalSessionsServices: terminalSessions, degradeServices: degrade });
  const setupUi = assembleSetupUi({ configEditorServices: configEditor, boardUiServices: boardUi, terminalWsServices: terminalWs });
  setupUi.serveSetupUi = lifetime.server(setupUi.serveSetupUi);
  const boardServe = assembleBoardServe({ setupUiServices: setupUi, claudeTrustServices: claudeTrust });
  const cacheRead = assembleCacheRead({ globalWorkStoreServices: globalWorkStore, workspaceServices: workspace, degradeServices: degrade });
  const workLoops = assembleWorkLoops({  });
  const workAcceptorCriterion = assembleWorkAcceptorCriterion({  });
  const meshWorktree = assembleMeshWorktree({ degradeServices: degrade, workServices: work, provideWorkToolchain: async () => { lifetime.assertReady(); return workToolchain; } });
  const effectsJournal = assembleEffectsJournal({ workspaceServices: workspace, degradeServices: degrade });
  effectsJournal.openEffectsJournal = lifetime.open(effectsJournal.openEffectsJournal);
  const workAcceptorObservations = assembleWorkAcceptorObservations({ meshWorktreeServices: meshWorktree, effectsJournalServices: effectsJournal });
  const effectsTable = assembleEffectsTable({ degradeServices: degrade, provideWork: async () => { lifetime.assertReady(); return work; }, provideRunStore: async () => { lifetime.assertReady(); return runStore; }, provideWorkAcceptorStore: async () => { lifetime.assertReady(); return workAcceptorStore; }, provideGlobalWorkPublisher: async () => { lifetime.assertReady(); return globalWorkPublisher; }, provideGlobalWorkStore: async () => { lifetime.assertReady(); return globalWorkStore; }, provideEffectsAssignmentTransitions: async () => { lifetime.assertReady(); return effectsAssignmentTransitions; }, provideMeshParkResume: async () => { lifetime.assertReady(); return meshParkResume; }, provideNotionSyncWork: async () => { lifetime.assertReady(); return notionSyncWork; }, provideNotionMapping: async () => { lifetime.assertReady(); return notionMapping; } });
  const effectsDispatch = assembleEffectsDispatch({ effectsTableServices: effectsTable, effectsJournalServices: effectsJournal, degradeServices: degrade });
  const workAcceptorStore = assembleWorkAcceptorStore({ workAcceptorCriterionServices: workAcceptorCriterion });
  const effectsHarnessTransitions = assembleEffectsHarnessTransitions({ effectsTableServices: effectsTable, effectsJournalServices: effectsJournal, effectsDispatchServices: effectsDispatch, degradeServices: degrade, workAcceptorStoreServices: workAcceptorStore });
  const commandsAcceptor = assembleCommandsAcceptor({ workLoopsServices: workLoops, workAcceptorCriterionServices: workAcceptorCriterion, workAcceptorObservationsServices: workAcceptorObservations, effectsJournalServices: effectsJournal, effectsHarnessTransitionsServices: effectsHarnessTransitions });
  const runStore = assembleRunStore({ degradeServices: degrade, provideWorkExamplesAnswers: async () => { lifetime.assertReady(); return workExamplesAnswers; } });
  const workContentRead = assembleWorkContentRead({ runStoreServices: runStore });
  const loopStopRequest = assembleLoopStopRequest({ workspaceServices: workspace, degradeServices: degrade });
  const meshPresence = assembleMeshPresence({ meshStoreServices: meshStore, runStoreServices: runStore, loopStopRequestServices: loopStopRequest, meshSessionServices: meshSession, globalWorkStoreServices: globalWorkStore, workspaceServices: workspace });
  const globalNodeRegistry = assembleGlobalNodeRegistry({ workspaceServices: workspace, meshStoreServices: meshStore, meshPresenceServices: meshPresence, degradeServices: degrade });
  const globalWorkPublisher = assembleGlobalWorkPublisher({ workspaceServices: workspace, globalWorkStoreServices: globalWorkStore, workContentReadServices: workContentRead, globalNodeRegistryServices: globalNodeRegistry, degradeServices: degrade });
  const itemLock = assembleItemLock({ workspaceServices: workspace, globalWorkStoreServices: globalWorkStore, globalWorkPublisherServices: globalWorkPublisher });
  const effectsStreamTransitions = assembleEffectsStreamTransitions({ itemLockServices: itemLock, effectsTableServices: effectsTable, effectsJournalServices: effectsJournal, effectsDispatchServices: effectsDispatch, degradeServices: degrade });
  const commandsArchive = assembleCommandsArchive({ effectsStreamTransitionsServices: effectsStreamTransitions });
  const workAuditCensus = assembleWorkAuditCensus({  });
  const workAuditEvidence = assembleWorkAuditEvidence({  });
  const workAuditPromptLayer = assembleWorkAuditPromptLayer({  });
  const workAuditSeamLiveness = assembleWorkAuditSeamLiveness({ workAuditCensusServices: workAuditCensus });
  const workAuditDeclaredBounds = assembleWorkAuditDeclaredBounds({  });
  const workAuditReport = assembleWorkAuditReport({ workAuditCensusServices: workAuditCensus, workAuditEvidenceServices: workAuditEvidence, workAuditPromptLayerServices: workAuditPromptLayer, workAuditSeamLivenessServices: workAuditSeamLiveness, workAuditDeclaredBoundsServices: workAuditDeclaredBounds });
  const commandsAudit = assembleCommandsAudit({ workLoopsServices: workLoops, workAuditReportServices: workAuditReport, workAuditPromptLayerServices: workAuditPromptLayer, workAuditDeclaredBoundsServices: workAuditDeclaredBounds });
  const workRead = assembleWorkRead({ cacheReadServices: cacheRead, degradeServices: degrade, meshWorktreeServices: meshWorktree });
  const effectsOutbox = assembleEffectsOutbox({ effectsJournalServices: effectsJournal, effectsDispatchServices: effectsDispatch, degradeServices: degrade });
  const effectsAssignmentTransitions = assembleEffectsAssignmentTransitions({ effectsTableServices: effectsTable, effectsJournalServices: effectsJournal, effectsDispatchServices: effectsDispatch, effectsOutboxServices: effectsOutbox, degradeServices: degrade });
  const meshAssignment = assembleMeshAssignment({ globalWorkStoreServices: globalWorkStore, workReadServices: workRead, effectsAssignmentTransitionsServices: effectsAssignmentTransitions, itemLockServices: itemLock });
  const commandsResolve = assembleCommandsResolve({ workReadServices: workRead, runStoreServices: runStore });
  const effectsItemTransitions = assembleEffectsItemTransitions({ workServices: work, effectsTableServices: effectsTable, effectsJournalServices: effectsJournal, effectsDispatchServices: effectsDispatch, degradeServices: degrade });
  const commandsContinue = assembleCommandsContinue({ meshAssignmentServices: meshAssignment, commandsResolveServices: commandsResolve, effectsItemTransitionsServices: effectsItemTransitions, boardMeshExecutionServices: boardMeshExecution, cacheReadServices: cacheRead });
  const runHeartbeatConsumption = assembleRunHeartbeatConsumption({ degradeServices: degrade, runStoreServices: runStore });
  const effectsRunTransitions = assembleEffectsRunTransitions({ runStoreServices: runStore, runHeartbeatConsumptionServices: runHeartbeatConsumption, effectsTableServices: effectsTable, effectsJournalServices: effectsJournal, effectsDispatchServices: effectsDispatch, degradeServices: degrade, itemLockServices: itemLock, workObserveServices: workObserve });
  const commandsRunRetry = assembleCommandsRunRetry({ commandsResolveServices: commandsResolve, effectsRunTransitionsServices: effectsRunTransitions, itemLockServices: itemLock });
  const commandsCounters = assembleCommandsCounters({ runStoreServices: runStore, commandsResolveServices: commandsResolve, commandsRunRetryServices: commandsRunRetry });
  const diagramsRasterize = assembleDiagramsRasterize({ degradeServices: degrade });
  const commandsDiagramExport = assembleCommandsDiagramExport({ configInspectServices: configInspect, commandsResolveServices: commandsResolve, diagramsRasterizeServices: diagramsRasterize });
  const commandsDiagramFile = assembleCommandsDiagramFile({ commandsResolveServices: commandsResolve });
  const commandsDiagramPlan = assembleCommandsDiagramPlan({ configInspectServices: configInspect, commandsResolveServices: commandsResolve });
  const meshLauncherLock = assembleMeshLauncherLock({ workspaceServices: workspace, degradeServices: degrade });
  const workDispatch = assembleWorkDispatch({ meshWorktreeServices: meshWorktree, workServices: work, degradeServices: degrade, meshLauncherLockServices: meshLauncherLock });
  const commandsDispatch = assembleCommandsDispatch({ workReadServices: workRead, effectsJournalServices: effectsJournal, effectsDispatchServices: effectsDispatch, workDispatchServices: workDispatch });
  const commandsDoc = assembleCommandsDoc({ commandsResolveServices: commandsResolve, cacheReadServices: cacheRead, workReadServices: workRead });
  const workDoctorDiagrams = assembleWorkDoctorDiagrams({ configInspectServices: configInspect });
  const workDoctor = assembleWorkDoctor({ runStoreServices: runStore, workDoctorDiagramsServices: workDoctorDiagrams });
  const effectsReconcile = assembleEffectsReconcile({ workServices: work, runStoreServices: runStore, effectsTableServices: effectsTable, effectsJournalServices: effectsJournal, degradeServices: degrade });
  const commandsDoctor = assembleCommandsDoctor({ workDoctorServices: workDoctor, cacheReadServices: cacheRead, workReadServices: workRead, effectsTableServices: effectsTable, effectsJournalServices: effectsJournal, effectsDispatchServices: effectsDispatch, effectsReconcileServices: effectsReconcile, provideCommandCore: async () => { lifetime.assertReady(); return commandCore; } });
  const loopAskRequest = assembleLoopAskRequest({ workspaceServices: workspace, degradeServices: degrade });
  const runSessionCapture = assembleRunSessionCapture({ runStoreServices: runStore, degradeServices: degrade });
  const runSpendIngest = assembleRunSpendIngest({ runStoreServices: runStore });
  const commandsDrive = assembleCommandsDrive({ agentSessionDriverServices: agentSessionDriver, claudeTrustServices: claudeTrust, degradeServices: degrade, runStoreServices: runStore, loopAskRequestServices: loopAskRequest, runHeartbeatConsumptionServices: runHeartbeatConsumption, effectsRunTransitionsServices: effectsRunTransitions, runSessionCaptureServices: runSessionCapture, commandsResolveServices: commandsResolve, workObserveServices: workObserve, runSpendIngestServices: runSpendIngest });
  const effectsDocTransitions = assembleEffectsDocTransitions({ effectsTableServices: effectsTable, effectsJournalServices: effectsJournal, effectsDispatchServices: effectsDispatch, degradeServices: degrade });
  const commandsFeedback = assembleCommandsFeedback({ commandsResolveServices: commandsResolve, effectsDocTransitionsServices: effectsDocTransitions, globalWorkPublisherServices: globalWorkPublisher });
  const commandsFind = assembleCommandsFind({ workReadServices: workRead });
  const commandsGrade = assembleCommandsGrade({ commandsResolveServices: commandsResolve, runStoreServices: runStore, meshWorktreeServices: meshWorktree });
  const graphify = assembleGraphify({  });
  const commandsGraphBuild = assembleCommandsGraphBuild({ graphifyServices: graphify });
  const commandsGraphQuery = assembleCommandsGraphQuery({ graphifyServices: graphify });
  const graphMcpServer = assembleGraphMcpServer({ commandCoreServices: commandPort });
  const commandsGraphServe = assembleCommandsGraphServe({ graphMcpServerServices: graphMcpServer, workServices: work });
  const commandsGraphTriage = assembleCommandsGraphTriage({ graphifyServices: graphify });
  const importStore = assembleImportStore({ workspaceServices: workspace });
  const importRecovery = assembleImportRecovery({ importStoreServices: importStore });
  const importMaterialize = assembleImportMaterialize({ importStoreServices: importStore, workDigestTemplateServices: workDigestTemplate, workServices: work });
  const workMemory = assembleWorkMemory({ provideMemoryLocalBackend: async () => { lifetime.assertReady(); return memoryLocalBackend; }, provideMemoryGraphifyBackend: async () => { lifetime.assertReady(); return memoryGraphifyBackend; } });
  const commandsImportMilestone = assembleCommandsImportMilestone({ importRecoveryServices: importRecovery, importMaterializeServices: importMaterialize, importStoreServices: importStore, workMemoryServices: workMemory });
  const commandsInsertShared = assembleCommandsInsertShared({ effectsStreamTransitionsServices: effectsStreamTransitions });
  const commandsPromote = assembleCommandsPromote({ effectsStreamTransitionsServices: effectsStreamTransitions, commandsInsertSharedServices: commandsInsertShared });
  const commandsInsertChore = assembleCommandsInsertChore({ commandsInsertSharedServices: commandsInsertShared, commandsPromoteServices: commandsPromote });
  const commandsInsertMilestone = assembleCommandsInsertMilestone({ commandsInsertSharedServices: commandsInsertShared, commandsPromoteServices: commandsPromote });
  const commandsInsertStory = assembleCommandsInsertStory({ commandsInsertSharedServices: commandsInsertShared });
  const commandsInsertUat = assembleCommandsInsertUat({ commandsInsertSharedServices: commandsInsertShared, commandsPromoteServices: commandsPromote });
  const notifySecret = assembleNotifySecret({  });
  const notifyAskMessages = assembleNotifyAskMessages({ notifySecretServices: notifySecret });
  const notifyNotify = assembleNotifyNotify({ degradeServices: degrade, notifyAskMessagesServices: notifyAskMessages, notifySecretServices: notifySecret });
  const commandsItemStatus = assembleCommandsItemStatus({ commandsResolveServices: commandsResolve, effectsItemTransitionsServices: effectsItemTransitions, globalWorkPublisherServices: globalWorkPublisher, workDoctorServices: workDoctor, meshWorktreeServices: meshWorktree, notifyNotifyServices: notifyNotify });
  const commandsList = assembleCommandsList({ workReadServices: workRead, boardMeshExecutionServices: boardMeshExecution, cacheReadServices: cacheRead, loopAskRequestServices: loopAskRequest, degradeServices: degrade });
  const commandsLoopDocument = assembleCommandsLoopDocument({ provideCommandCore: async () => { lifetime.assertReady(); return commandCore; } });
  const commandsLoopRecord = assembleCommandsLoopRecord({ workLoopsServices: workLoops, runStoreServices: runStore, commandsResolveServices: commandsResolve });
  const loopProgress = assembleLoopProgress({ degradeServices: degrade, workDispatchServices: workDispatch });
  const loopChildDrive = assembleLoopChildDrive({ workspaceServices: workspace });
  const loopAsk = assembleLoopAsk({ loopAskRequestServices: loopAskRequest, runStoreServices: runStore, runHeartbeatConsumptionServices: runHeartbeatConsumption, workObserveServices: workObserve, notifyNotifyServices: notifyNotify, degradeServices: degrade });
  const loopCycle = assembleLoopCycle({ commandsResolveServices: commandsResolve, loopChildDriveServices: loopChildDrive, loopAskServices: loopAsk, loopAskRequestServices: loopAskRequest, workDispatchServices: workDispatch, meshWorktreeServices: meshWorktree, loopProgressServices: loopProgress, commandsGradeServices: commandsGrade, itemLockServices: itemLock, runStoreServices: runStore, effectsRunTransitionsServices: effectsRunTransitions, degradeServices: degrade, runSpendIngestServices: runSpendIngest, provideCommandCore: async () => { lifetime.assertReady(); return commandCore; } });
  const loopWave = assembleLoopWave({ workServices: work, runStoreServices: runStore, runHeartbeatConsumptionServices: runHeartbeatConsumption, effectsRunTransitionsServices: effectsRunTransitions, degradeServices: degrade, workDispatchServices: workDispatch, meshWorktreeServices: meshWorktree, loopChildDriveServices: loopChildDrive, loopAskServices: loopAsk, loopCycleServices: loopCycle, provideCommandCore: async () => { lifetime.assertReady(); return commandCore; } });
  const loopDiag = assembleLoopDiag({ workspaceServices: workspace, degradeServices: degrade });
  const loopStop = assembleLoopStop({ workServices: work, runStoreServices: runStore, loopStopRequestServices: loopStopRequest });
  const commandsLoop = assembleCommandsLoop({ workServices: work, loopProgressServices: loopProgress, loopCycleServices: loopCycle, commandsResolveServices: commandsResolve, commandsGradeServices: commandsGrade, runStoreServices: runStore, effectsRunTransitionsServices: effectsRunTransitions, degradeServices: degrade, meshWorktreeServices: meshWorktree, loopWaveServices: loopWave, loopChildDriveServices: loopChildDrive, loopAskServices: loopAsk, loopDiagServices: loopDiag, notifyNotifyServices: notifyNotify, loopStopServices: loopStop, loopStopRequestServices: loopStopRequest, provideCommandCore: async () => { lifetime.assertReady(); return commandCore; } });
  const commandsLoopsGraph = assembleCommandsLoopsGraph({ workLoopsServices: workLoops });
  const commandsLoopsGroundedness = assembleCommandsLoopsGroundedness({ workLoopsServices: workLoops });
  const commandsLoopsShow = assembleCommandsLoopsShow({ workLoopsServices: workLoops });
  const commandsLoopsValidate = assembleCommandsLoopsValidate({ workLoopsServices: workLoops });
  const commandsMeshAssign = assembleCommandsMeshAssign({ meshAssignmentServices: meshAssignment });
  const meshRegistry = assembleMeshRegistry({ meshStoreServices: meshStore });
  const commandsMeshIdentity = assembleCommandsMeshIdentity({ meshStoreServices: meshStore, meshPresenceServices: meshPresence, meshRegistryServices: meshRegistry, provideMeshDeclarations: async () => { lifetime.assertReady(); return meshDeclarations; } });
  const commandsMeshHeartbeat = assembleCommandsMeshHeartbeat({ workReadServices: workRead, cacheReadServices: cacheRead, commandsMeshIdentityServices: commandsMeshIdentity, meshPresenceServices: meshPresence });
  const meshRelay = assembleMeshRelay({ meshRegistryServices: meshRegistry, meshStoreServices: meshStore, degradeServices: degrade });
  const commandsMeshRelay = assembleCommandsMeshRelay({ meshRelayServices: meshRelay });
  const commandsMeshInvite = assembleCommandsMeshInvite({ meshRegistryServices: meshRegistry, meshRelayServices: meshRelay });
  const commandsMeshJoin = assembleCommandsMeshJoin({ workspaceServices: workspace, meshStoreServices: meshStore, degradeServices: degrade });
  const commandsMeshRevoke = assembleCommandsMeshRevoke({ meshRegistryServices: meshRegistry });
  const meshTerminalRelayBridge = assembleMeshTerminalRelayBridge({ degradeServices: degrade });
  const meshRecoveryPush = assembleMeshRecoveryPush({ meshWorktreeServices: meshWorktree, provideGlobalWorkStore: async () => { lifetime.assertReady(); return globalWorkStore; } });
  const meshResync = assembleMeshResync({ provideGlobalWorkStore: async () => { lifetime.assertReady(); return globalWorkStore; } });
  const workerStreamClient = assembleWorkerStreamClient({ meshTerminalRelayBridgeServices: meshTerminalRelayBridge, meshRecoveryPushServices: meshRecoveryPush, meshResyncServices: meshResync, degradeServices: degrade });
  const meshRelayClient = assembleMeshRelayClient({ degradeServices: degrade });
  const controlStreamServer = assembleControlStreamServer({ globalWorkStoreServices: globalWorkStore, globalNodeRegistryServices: globalNodeRegistry, meshPresenceServices: meshPresence, effectsAssignmentTransitionsServices: effectsAssignmentTransitions, effectsTableServices: effectsTable, effectsJournalServices: effectsJournal, effectsDispatchServices: effectsDispatch, meshTerminalRelayBridgeServices: meshTerminalRelayBridge, meshRelayClientServices: meshRelayClient, meshRecoveryPushServices: meshRecoveryPush, meshResyncServices: meshResync, degradeServices: degrade });
  const meshParkResume = assembleMeshParkResume({ runStoreServices: runStore, workObserveServices: workObserve, effectsAssignmentTransitionsServices: effectsAssignmentTransitions, effectsRunTransitionsServices: effectsRunTransitions, degradeServices: degrade, provideMeshPresence: async () => { lifetime.assertReady(); return meshPresence; }, provideWork: async () => { lifetime.assertReady(); return work; }, provideNotifyNotify: async () => { lifetime.assertReady(); return notifyNotify; } });
  const meshWorkerLaunch = assembleMeshWorkerLaunch({  });
  const meshWorkerRepoAdmission = assembleMeshWorkerRepoAdmission({ workServices: work, workspaceServices: workspace, globalWorkStoreServices: globalWorkStore });
  const meshWorkerExecution = assembleMeshWorkerExecution({ workServices: work, runStoreServices: runStore, runSessionCaptureServices: runSessionCapture, effectsRunTransitionsServices: effectsRunTransitions, effectsAssignmentTransitionsServices: effectsAssignmentTransitions, meshParkResumeServices: meshParkResume, meshWorktreeServices: meshWorktree, workDispatchServices: workDispatch, meshPresenceServices: meshPresence, agentSessionDriverServices: agentSessionDriver, degradeServices: degrade, runHeartbeatConsumptionServices: runHeartbeatConsumption, meshWorkerLaunchServices: meshWorkerLaunch, meshWorkerRepoAdmissionServices: meshWorkerRepoAdmission });
  const meshSessionSpawnHandler = assembleMeshSessionSpawnHandler({ terminalWsServices: terminalWs, meshWorktreeServices: meshWorktree, meshSessionServices: meshSession, workServices: work, degradeServices: degrade });
  const meshTerminalMirror = assembleMeshTerminalMirror({ meshRelayServices: meshRelay, meshTerminalRelayBridgeServices: meshTerminalRelayBridge, workerStreamClientServices: workerStreamClient, degradeServices: degrade });
  const meshTerminalInput = assembleMeshTerminalInput({ meshTerminalRelayBridgeServices: meshTerminalRelayBridge, degradeServices: degrade });
  const meshAssignmentReclaim = assembleMeshAssignmentReclaim({ meshPresenceServices: meshPresence, runStoreServices: runStore, runHeartbeatConsumptionServices: runHeartbeatConsumption, workReadServices: workRead, effectsAssignmentTransitionsServices: effectsAssignmentTransitions, effectsRunTransitionsServices: effectsRunTransitions, globalWorkStoreServices: globalWorkStore, meshWorktreeServices: meshWorktree, degradeServices: degrade, workDispatchServices: workDispatch });
  const meshCloneCredentialProvider = assembleMeshCloneCredentialProvider({ controlStreamServerServices: controlStreamServer });
  const meshLauncher = assembleMeshLauncher({ workspaceServices: workspace, meshStoreServices: meshStore, meshPresenceServices: meshPresence, workServices: work, workReadServices: workRead, cacheReadServices: cacheRead, globalWorkPublisherServices: globalWorkPublisher, workerStreamClientServices: workerStreamClient, controlStreamServerServices: controlStreamServer, meshWorkerExecutionServices: meshWorkerExecution, meshSessionSpawnHandlerServices: meshSessionSpawnHandler, meshRecoveryPushServices: meshRecoveryPush, meshResyncServices: meshResync, meshRelayServices: meshRelay, meshRegistryServices: meshRegistry, meshLauncherLockServices: meshLauncherLock, meshTerminalRelayBridgeServices: meshTerminalRelayBridge, meshTerminalMirrorServices: meshTerminalMirror, meshTerminalInputServices: meshTerminalInput, meshAssignmentReclaimServices: meshAssignmentReclaim, meshCloneCredentialProviderServices: meshCloneCredentialProvider, degradeServices: degrade, effectsJournalServices: effectsJournal, effectsOutboxServices: effectsOutbox, effectsAssignmentTransitionsServices: effectsAssignmentTransitions, provideNotifyNotify: async () => { lifetime.assertReady(); return notifyNotify; }, provideDiscordBot: async () => { lifetime.assertReady(); return discordBot; } });
  meshLauncher.startLauncher = lifetime.start(meshLauncher.startLauncher);
  const commandsMeshServe = assembleCommandsMeshServe({ meshLauncherServices: meshLauncher, meshLauncherLockServices: meshLauncherLock, diagnosticsLogServices: diagnosticsLog, workspaceServices: workspace, workServices: work, fsServices: fs });
  const commandsMeshLogs = assembleCommandsMeshLogs({ diagnosticsLogServices: diagnosticsLog, globalWorkStoreServices: globalWorkStore, workspaceServices: workspace });
  const commandsMeshTerminalResume = assembleCommandsMeshTerminalResume({ globalWorkStoreServices: globalWorkStore, meshAssignmentReclaimServices: meshAssignmentReclaim, workDispatchServices: workDispatch, workspaceServices: workspace, meshTerminalRelayBridgeServices: meshTerminalRelayBridge, effectsJournalServices: effectsJournal, degradeServices: degrade });
  const commandsMeshRecoverPush = assembleCommandsMeshRecoverPush({ globalWorkStoreServices: globalWorkStore, workspaceServices: workspace, meshRecoveryPushServices: meshRecoveryPush });
  const commandsMeshRepo = assembleCommandsMeshRepo({ globalWorkPublisherServices: globalWorkPublisher });
  const globalMeshQuery = assembleGlobalMeshQuery({ workspaceServices: workspace, globalWorkStoreServices: globalWorkStore, globalNodeRegistryServices: globalNodeRegistry, globalWorkPublisherServices: globalWorkPublisher });
  const meshUiServe = assembleMeshUiServe({ boardServeServices: boardServe, globalMeshQueryServices: globalMeshQuery, workServices: work, meshAssignmentServices: meshAssignment, loopStopServices: loopStop, meshTerminalMirrorServices: meshTerminalMirror, meshTerminalRelayBridgeServices: meshTerminalRelayBridge, terminalProvidersServices: terminalProviders, degradeServices: degrade });
  meshUiServe.serveMeshUi = lifetime.server(meshUiServe.serveMeshUi);
  const commandsMeshUi = assembleCommandsMeshUi({ meshUiServeServices: meshUiServe, meshTerminalMirrorServices: meshTerminalMirror, meshTerminalRelayBridgeServices: meshTerminalRelayBridge, diagnosticsLogServices: diagnosticsLog, workServices: work });
  const commandsMeshDesktopPreflight = assembleCommandsMeshDesktopPreflight({ meshPresenceServices: meshPresence, workspaceServices: workspace });
  const commandsMeshDesktop = assembleCommandsMeshDesktop({ commandsMeshDesktopPreflightServices: commandsMeshDesktopPreflight });
  const commandsMeshContribution = assembleCommandsMeshContribution({ commandsMeshIdentityServices: commandsMeshIdentity, commandsMeshHeartbeatServices: commandsMeshHeartbeat, commandsMeshRelayServices: commandsMeshRelay, commandsMeshInviteServices: commandsMeshInvite, commandsMeshJoinServices: commandsMeshJoin, commandsMeshRevokeServices: commandsMeshRevoke, commandsMeshServeServices: commandsMeshServe, commandsMeshLogsServices: commandsMeshLogs, commandsMeshTerminalResumeServices: commandsMeshTerminalResume, commandsMeshAssignServices: commandsMeshAssign, commandsMeshRecoverPushServices: commandsMeshRecoverPush, commandsMeshRepoServices: commandsMeshRepo, commandsMeshUiServices: commandsMeshUi, commandsMeshDesktopServices: commandsMeshDesktop });
  const commandsMessagingMessaging = assembleCommandsMessagingMessaging({ notifyNotifyServices: notifyNotify, notifySecretServices: notifySecret });
  const commandsMigrateFolder = assembleCommandsMigrateFolder({ importRecoveryServices: importRecovery, importStoreServices: importStore });
  const commandsNext = assembleCommandsNext({ workReadServices: workRead, itemLockServices: itemLock });
  const integrationsRouting = assembleIntegrationsRouting({ degradeServices: degrade });
  const commandsNotionAssociate = assembleCommandsNotionAssociate({ workReadServices: workRead, commandsResolveServices: commandsResolve, integrationsRoutingServices: integrationsRouting });
  const notionMapping = assembleNotionMapping({ workspaceServices: workspace });
  const notionSync = assembleNotionSync({ notionMappingServices: notionMapping });
  const notionCli = assembleNotionCli({ degradeServices: degrade });
  const notionSyncWork = assembleNotionSyncWork({ workServices: work, workReadServices: workRead, notionMappingServices: notionMapping, notionSyncServices: notionSync, notionCliServices: notionCli, integrationsRoutingServices: integrationsRouting });
  const commandsNotionSyncWork = assembleCommandsNotionSyncWork({ notionSyncWorkServices: notionSyncWork, effectsJournalServices: effectsJournal, effectsDispatchServices: effectsDispatch, degradeServices: degrade });
  const commandsObserve = assembleCommandsObserve({ workObserveServices: workObserve, workServices: work });
  const commandsPromoteFindingToChore = assembleCommandsPromoteFindingToChore({ commandsPromoteServices: commandsPromote, workReadServices: workRead });
  const commandsPromoteGapToChore = assembleCommandsPromoteGapToChore({ commandsInsertSharedServices: commandsInsertShared, commandsPromoteServices: commandsPromote });
  const commandsRatchet = assembleCommandsRatchet({ commandsResolveServices: commandsResolve });
  const workTestSelect = assembleWorkTestSelect({ workAuditCensusServices: workAuditCensus });
  const workTestChanged = assembleWorkTestChanged({ workTestSelectServices: workTestSelect });
  const workToolchain = assembleWorkToolchain({  });
  const commandsTest = assembleCommandsTest({ workAuditCensusServices: workAuditCensus, workTestChangedServices: workTestChanged, commandsResolveServices: commandsResolve, workTestSelectServices: workTestSelect, workToolchainServices: workToolchain });
  const commandsRegressionGate = assembleCommandsRegressionGate({ meshWorktreeServices: meshWorktree, commandsResolveServices: commandsResolve, commandsTestServices: commandsTest });
  const commandsResume = assembleCommandsResume({ commandsResolveServices: commandsResolve, runStoreServices: runStore, effectsRunTransitionsServices: effectsRunTransitions, workReadServices: workRead, itemLockServices: itemLock, loopAskRequestServices: loopAskRequest, loopAskServices: loopAsk, boardMeshExecutionServices: boardMeshExecution, notifyNotifyServices: notifyNotify, provideCommandCore: async () => { lifetime.assertReady(); return commandCore; } });
  const commandsResync = assembleCommandsResync({ globalWorkStoreServices: globalWorkStore, workspaceServices: workspace, meshResyncServices: meshResync });
  const commandsRunComplete = assembleCommandsRunComplete({ commandsResolveServices: commandsResolve, effectsRunTransitionsServices: effectsRunTransitions, runStoreServices: runStore, globalWorkPublisherServices: globalWorkPublisher });
  const commandsRunStart = assembleCommandsRunStart({ commandsResolveServices: commandsResolve, workReadServices: workRead, runStoreServices: runStore, meshPresenceServices: meshPresence, effectsRunTransitionsServices: effectsRunTransitions, globalWorkPublisherServices: globalWorkPublisher, itemLockServices: itemLock, meshSessionServices: meshSession });
  const commandsRunStatus = assembleCommandsRunStatus({ commandsResolveServices: commandsResolve, runStoreServices: runStore, cacheReadServices: cacheRead, boardMeshExecutionServices: boardMeshExecution });
  const commandsTasks = assembleCommandsTasks({ commandsResolveServices: commandsResolve, cacheReadServices: cacheRead, workReadServices: workRead });
  const workTriggerDeclaration = assembleWorkTriggerDeclaration({ workLoopsServices: workLoops });
  const commandsTrigger = assembleCommandsTrigger({ workTriggerDeclarationServices: workTriggerDeclaration, provideCommandCore: async () => { lifetime.assertReady(); return commandCore; } });
  const memoryLocalIndexing = assembleMemoryLocalIndexing({ workReadServices: workRead, importStoreServices: importStore, importMaterializeServices: importMaterialize });
  const workTuneCorpus = assembleWorkTuneCorpus({ memoryLocalIndexingServices: memoryLocalIndexing, runStoreServices: runStore, workObserveServices: workObserve, workLoopsServices: workLoops });
  const workTuneProposal = assembleWorkTuneProposal({  });
  const commandsTune = assembleCommandsTune({ workTuneCorpusServices: workTuneCorpus, workTuneProposalServices: workTuneProposal, workLoopsServices: workLoops, provideCommandCore: async () => { lifetime.assertReady(); return commandCore; } });
  const workUpgrade = assembleWorkUpgrade({  });
  const commandsUpgrade = assembleCommandsUpgrade({ workUpgradeServices: workUpgrade });
  const commandsValidate = assembleCommandsValidate({ commandsDoctorServices: commandsDoctor, workServices: work });
  const commandsWorkMemory = assembleCommandsWorkMemory({ workMemoryServices: workMemory });
  const commandsWorkUi = assembleCommandsWorkUi({ boardServeServices: boardServe, meshUiServeServices: meshUiServe });
  const discordCommands = assembleDiscordCommands({ degradeServices: degrade, notifyAskMessagesServices: notifyAskMessages, loopStopRequestServices: loopStopRequest, provideLoopStop: async () => { lifetime.assertReady(); return loopStop; } });
  const discordGateway = assembleDiscordGateway({ degradeServices: degrade });
  const discordReplies = assembleDiscordReplies({ loopAskRequestServices: loopAskRequest, notifyAskMessagesServices: notifyAskMessages });
  const discordBot = assembleDiscordBot({ degradeServices: degrade, discordCommandsServices: discordCommands, discordGatewayServices: discordGateway, discordRepliesServices: discordReplies, provideCommandCore: async () => { lifetime.assertReady(); return commandCore; }, provideWork: async () => { lifetime.assertReady(); return work; }, provideMeshPresence: async () => { lifetime.assertReady(); return meshPresence; }, provideWorkAcceptorObservations: async () => { lifetime.assertReady(); return workAcceptorObservations; } });
  const memoryGraphifyBackend = assembleMemoryGraphifyBackend({ commandCoreServices: commandPort, memoryLocalIndexingServices: memoryLocalIndexing });
  const memoryLocalBackend = assembleMemoryLocalBackend({ memoryLocalIndexingServices: memoryLocalIndexing });
  const meshDeclarations = assembleMeshDeclarations({ meshPresenceServices: meshPresence, runStoreServices: runStore, commandsRunRetryServices: commandsRunRetry, workServices: work, loopStopRequestServices: loopStopRequest, provideCommandCore: async () => { lifetime.assertReady(); return commandCore; } });
  const storyContractDerive = assembleStoryContractDerive({  });
  const workExamplesAnswers = assembleWorkExamplesAnswers({ agentSessionDriverServices: agentSessionDriver, degradeServices: degrade, runStoreServices: runStore, runSpendIngestServices: runSpendIngest, workObserveServices: workObserve });
  const workInit = assembleWorkInit({ workspaceServices: workspace, workMemoryServices: workMemory });
  const commandsInitUpdate = assembleCommandsInitUpdate({ workInitServices: workInit, workMemoryServices: workMemory });
  const commandsAssetsUi = assembleCommandsAssetsUi({ provideSetupUi: async () => { lifetime.assertReady(); return setupUi; } });
  const spineFace = assembleSpineFace({ commandCoreServices: commandPort, effectsJournalServices: effectsJournal, effectsDispatchServices: effectsDispatch, degradeServices: degrade, provideGlobalWorkStore: async () => { lifetime.assertReady(); return globalWorkStore; }, applicationEnv: env });
  const scaffold = assembleScaffold({ fsServices: fs, workspaceServices: workspace });
  const commandsAssetsShow = assembleCommandsAssetsShow({ fsServices: fs, workspaceServices: workspace });
  const commandsAssetsRemove = assembleCommandsAssetsRemove({ fsServices: fs, workspaceServices: workspace });
  const commandsAssetsAdd = assembleCommandsAssetsAdd({ provideScaffold: async () => { lifetime.assertReady(); return scaffold; } });
  const commandsValidateShared = assembleCommandsValidateShared({ configInspectServices: configInspect });
  const commandsAssetsApply = assembleCommandsAssetsApply({ fsServices: fs, dslServices: dsl, workspaceServices: workspace, configInspectServices: configInspect, commandsValidateSharedServices: commandsValidateShared });
  const commandsAssetsList = assembleCommandsAssetsList({ configInspectServices: configInspect });
  const commandsAssetsRefs = assembleCommandsAssetsRefs({ configEditorServices: configEditor, workspaceServices: workspace });
  const commandsPackagesInstall = assembleCommandsPackagesInstall({ dslServices: dsl, workspaceServices: workspace });
  const commandsPackagesList = assembleCommandsPackagesList({ dslServices: dsl, workspaceServices: workspace });
  const commandsPackagesShow = assembleCommandsPackagesShow({ dslServices: dsl, workspaceServices: workspace });
  const commandsProjectDoctor = assembleCommandsProjectDoctor({ configInspectServices: configInspect, commandsValidateSharedServices: commandsValidateShared });
  const workspaceWriter = assembleWorkspaceWriter({ fsServices: fs, configEditorServices: configEditor, workspaceServices: workspace });
  const commandsProjectMigrate = assembleCommandsProjectMigrate({ dslServices: dsl, fsServices: fs, workspaceServices: workspace, workspaceWriterServices: workspaceWriter });
  const commandsProjectShow = assembleCommandsProjectShow({ configInspectServices: configInspect });
  const sync = assembleSync({ dslServices: dsl, workspaceServices: workspace });
  const commandsAssetsValidate = assembleCommandsAssetsValidate({ commandsValidateSharedServices: commandsValidateShared });
  const commandsPackagesValidate = assembleCommandsPackagesValidate({ fsServices: fs, workspaceServices: workspace, commandsValidateSharedServices: commandsValidateShared });
  const commandsProjectInit = assembleCommandsProjectInit({ fsServices: fs, workspaceWriterServices: workspaceWriter, workspaceServices: workspace });
  const commandsProjectValidate = assembleCommandsProjectValidate({ commandsValidateSharedServices: commandsValidateShared });
  const commandCore = assembleCommandCore({ commandsMeshContributionServices: commandsMeshContribution, workServices: work, commandsListServices: commandsList, commandsLoopsShowServices: commandsLoopsShow, commandsLoopsGraphServices: commandsLoopsGraph, commandsLoopsValidateServices: commandsLoopsValidate, commandsLoopsGroundednessServices: commandsLoopsGroundedness, commandsLoopDocumentServices: commandsLoopDocument, commandsLoopRecordServices: commandsLoopRecord, commandsContinueServices: commandsContinue, commandsDriveServices: commandsDrive, commandsLoopServices: commandsLoop, commandsResyncServices: commandsResync, commandsDocServices: commandsDoc, commandsTasksServices: commandsTasks, commandsValidateServices: commandsValidate, commandsNextServices: commandsNext, commandsDispatchServices: commandsDispatch, commandsFeedbackServices: commandsFeedback, commandsDoctorServices: commandsDoctor, commandsAuditServices: commandsAudit, commandsAcceptorServices: commandsAcceptor, commandsTuneServices: commandsTune, commandsTriggerServices: commandsTrigger, commandsGradeServices: commandsGrade, commandsRatchetServices: commandsRatchet, commandsCountersServices: commandsCounters, commandsGraphBuildServices: commandsGraphBuild, commandsGraphQueryServices: commandsGraphQuery, commandsGraphTriageServices: commandsGraphTriage, commandsTestServices: commandsTest, commandsImportMilestoneServices: commandsImportMilestone, commandsMigrateFolderServices: commandsMigrateFolder, commandsNotionSyncWorkServices: commandsNotionSyncWork, commandsNotionAssociateServices: commandsNotionAssociate, commandsRunStartServices: commandsRunStart, commandsRunCompleteServices: commandsRunComplete, commandsRunStatusServices: commandsRunStatus, commandsItemStatusServices: commandsItemStatus, commandsRegressionGateServices: commandsRegressionGate, commandsRunRetryServices: commandsRunRetry, commandsResumeServices: commandsResume, commandsGraphServeServices: commandsGraphServe, commandsDiagramPlanServices: commandsDiagramPlan, commandsDiagramExportServices: commandsDiagramExport, commandsDiagramFileServices: commandsDiagramFile, commandsMessagingMessagingServices: commandsMessagingMessaging, commandsWorkUiServices: commandsWorkUi, commandsAssetsUiServices: commandsAssetsUi, commandsFindServices: commandsFind, commandsObserveServices: commandsObserve, commandsWorkMemoryServices: commandsWorkMemory, commandsInitUpdateServices: commandsInitUpdate, commandsProjectInitServices: commandsProjectInit, commandsInsertMilestoneServices: commandsInsertMilestone, commandsInsertUatServices: commandsInsertUat, commandsInsertStoryServices: commandsInsertStory, commandsInsertChoreServices: commandsInsertChore, commandsPromoteServices: commandsPromote, commandsArchiveServices: commandsArchive, commandsPromoteGapToChoreServices: commandsPromoteGapToChore, commandsPromoteFindingToChoreServices: commandsPromoteFindingToChore, commandsUpgradeServices: commandsUpgrade, commandsAssetsListServices: commandsAssetsList, commandsPackagesListServices: commandsPackagesList, commandsProjectShowServices: commandsProjectShow, commandsAssetsShowServices: commandsAssetsShow, commandsAssetsAddServices: commandsAssetsAdd, commandsAssetsRemoveServices: commandsAssetsRemove, commandsAssetsRefsServices: commandsAssetsRefs, commandsAssetsValidateServices: commandsAssetsValidate, commandsAssetsApplyServices: commandsAssetsApply, commandsPackagesShowServices: commandsPackagesShow, commandsPackagesValidateServices: commandsPackagesValidate, commandsPackagesInstallServices: commandsPackagesInstall, commandsProjectValidateServices: commandsProjectValidate, commandsProjectDoctorServices: commandsProjectDoctor, commandsProjectMigrateServices: commandsProjectMigrate });
  lifetime.ready();
  const application = Object.freeze({
    ...commandPort,
    paths: workspace,
    cli: spineFace,
    execution: Object.freeze({ runs: runStore, transitions: effectsRunTransitions, sessions: agentSessionDriver }),
    effects: Object.freeze({ journal: effectsJournal, reactors: effectsTable, dispatcher: effectsDispatch, outbox: effectsOutbox, reconcile: effectsReconcile }),
    work: Object.freeze({ records: work, items: effectsItemTransitions, documents: effectsDocTransitions, streams: effectsStreamTransitions, harness: effectsHarnessTransitions }),
    mesh: Object.freeze({ store: globalWorkStore, worker: meshWorkerExecution, assignments: meshAssignment, transitions: effectsAssignmentTransitions, launcher: meshLauncher, locks: itemLock }),
    server: Object.freeze({ board: boardUi, mcp: graphMcpServer, serve: boardServe }),
    async close() {
      try { await lifetime.close(); }
      finally { for (const entry of meshWorkerExecution.listActiveWorktrees()) meshWorkerExecution.clearActiveWorktree(entry.assignmentId); }
    },
  });
  // Temporary named exports for pre-migration import paths; never supplied to features.
  const compatibility = { agentSessionDriver, boardMeshExecution, boardServe, boardUi, cacheRead, claudeTrust, commandsAcceptor, commandsArchive, commandsAudit, commandsContinue, commandsCounters, commandsDiagramExport, commandsDiagramFile, commandsDiagramPlan, commandsDispatch, commandsDoc, commandsDoctor, commandsDrive, commandsFeedback, commandsFind, commandsGrade, commandsGraphBuild, commandsGraphQuery, commandsGraphServe, commandsGraphTriage, commandsImportMilestone, commandsInsertChore, commandsInsertMilestone, commandsInsertShared, commandsInsertStory, commandsInsertUat, commandsItemStatus, commandsList, commandsLoopDocument, commandsLoopRecord, commandsLoop, commandsLoopsGraph, commandsLoopsGroundedness, commandsLoopsShow, commandsLoopsValidate, commandsMeshAssign, commandsMeshContribution, commandsMeshDesktopPreflight, commandsMeshDesktop, commandsMeshHeartbeat, commandsMeshIdentity, commandsMeshInvite, commandsMeshJoin, commandsMeshLogs, commandsMeshRecoverPush, commandsMeshRelay, commandsMeshRepo, commandsMeshRevoke, commandsMeshServe, commandsMeshSession, commandsMeshTerminalResume, commandsMeshUi, commandsMessagingMessaging, commandsMigrateFolder, commandsNext, commandsNotionAssociate, commandsNotionSyncWork, commandsObserve, commandsPromoteFindingToChore, commandsPromoteGapToChore, commandsPromote, commandsRatchet, commandsRegressionGate, commandsResolve, commandsResume, commandsResync, commandsRunComplete, commandsRunRetry, commandsRunStart, commandsRunStatus, commandsTasks, commandsTest, commandsTrigger, commandsTune, commandsUpgrade, commandsValidate, commandsWorkMemory, commandsWorkUi, controlStreamServer, degrade, diagnosticsLog, diagramsRasterize, discordBot, discordCommands, discordGateway, discordReplies, effectsAssignmentTransitions, effectsDocTransitions, effectsHarnessTransitions, effectsItemTransitions, effectsJournal, effectsOutbox, effectsReconcile, effectsRunTransitions, effectsStreamTransitions, fs, globalMeshQuery, globalNodeRegistry, globalWorkPublisher, globalWorkStore, graphMcpServer, graphify, importMaterialize, importRecovery, importStore, integrationsRouting, itemLock, loopAskRequest, loopAsk, loopChildDrive, loopCycle, loopStopRequest, loopStop, loopWave, loopDiag, loopProgress, memoryGraphifyBackend, memoryLocalBackend, memoryLocalIndexing, meshAssignmentReclaim, meshAssignment, meshCloneCredentialProvider, meshDeclarations, meshLauncherLock, meshLauncher, meshParkResume, meshPresence, meshRecoveryPush, meshRegistry, meshRelayClient, meshRelay, meshResync, meshSessionSpawnHandler, meshSession, meshStore, meshTerminalInput, meshTerminalMirror, meshTerminalRelayBridge, meshUiServe, meshWorkerExecution, meshWorkerLaunch, meshWorkerRepoAdmission, meshWorktree, notifyAskMessages, notifyNotify, notifySecret, notionCli, notionMapping, notionSyncWork, notionSync, runHeartbeatConsumption, runSessionCapture, runSpendIngest, runStore, setupUi, storyContractDerive, terminalScreen, terminalSessionScreen, terminalProviders, terminalSessions, terminalWs, workContentRead, workDigestTemplate, workDispatch, workDoctorDiagrams, workDoctor, workLoops, workMemory, workObserve, workRead, workTestChanged, workTestSelect, workToolchain, workUpgrade, workAcceptorCriterion, workAcceptorObservations, workAcceptorStore, workAuditCensus, workAuditDeclaredBounds, workAuditEvidence, workAuditPromptLayer, workAuditReport, workAuditSeamLiveness, workExamplesAnswers, workTriggerDeclaration, workTuneCorpus, workTuneProposal, workerStreamClient, effectsTable, effectsDispatch, work, workInit, commandsInitUpdate, commandsAssetsUi, commandCore, spineFace, configInspect, configEditor, dsl, scaffold, commandsAssetsShow, commandsAssetsRemove, commandsAssetsAdd, commandsAssetsApply, commandsAssetsList, commandsAssetsRefs, commandsPackagesInstall, commandsPackagesList, commandsPackagesShow, commandsProjectDoctor, commandsProjectMigrate, commandsProjectShow, commandsValidateShared, sync, workspaceWriter, commandsAssetsValidate, commandsPackagesValidate, commandsProjectInit, commandsProjectValidate };
  return { application, compatibility };
}

export function createApplication(options) {
  return assembleApplication(options).application;
}
